// Auto-generated by dynamic_regress/run_pipeline.py.
// RTOSAlgorithm-style wrapper for the identified Pinocchio/CasADi dynamics.
#pragma once

#include "hansTypes.h"
#include "dynamicsBase.h"

using namespace KDL;

class constrainedFullCompareDynamics : public dynamicsBase
{
public:
	constrainedFullCompareDynamics();
	virtual ~constrainedFullCompareDynamics();

	virtual void setRobotDHParameters
	(
		const EcRealVector& kinematcisParam
	);

	virtual void setGravityVector
	(
		const EcReal gx, const EcReal gy, const EcReal gz
	);

	virtual void calculateGravityJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	virtual EcBoolean calculateEstimateJointToqrues
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	void computeRigidTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeMassTorque
	(
		const EcRealVector& q,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeCoriolisTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		EcRealVector& tau
	) const;

	void computeGravityAxisTorques
	(
		const EcRealVector& q,
		EcRealVector& tauGxUnit,
		EcRealVector& tauGyUnit,
		EcRealVector& tauGzUnit
	) const;

	void computeFrictionTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeInverseDynamics
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	virtual void calculateMomentumEstimatedJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

private:
	static const EcSizeT kNumJoints = 7;
	EcSizeT m_NumJoints;
	EcReal m_gx;
	EcReal m_gy;
	EcReal m_gz;
	EcRealVector m_zeros;
};
