// Auto-generated by dynamic_regress/run_pipeline.py.
// RTOSAlgorithm-style wrapper for the identified Pinocchio/CasADi dynamics.
// generated_at: 2026-04-30T17:10:19
// robot_name: 05_urdf
// data_source: real
// real_torque_source: sensed
// parameterization: base
// identification_mode: rigid_body_friction
// payload_mode: none
// nonlinear_compensation: disabled_for_export
#pragma once

#include "hansTypes.h"
#include "dynamicsBase.h"

using namespace KDL;

enum RuntimeTorqueMode
{
	LEGACY_RAW = 0,
	ROBUST_NO_TIME = 1,
	ROBUST_TIMED_RESERVED = 2
};

enum MotionState
{
	STATIC = 0,
	MOVING_POSITIVE = 1,
	MOVING_NEGATIVE = 2,
	TRANSITION = 3
};

struct RuntimeNoTimeConfig
{
	EcBoolean enableInputValidation = true;
	EcBoolean enableSampleSmoothing = false;
	EcBoolean enableDdqClamp = false;
	EcBoolean enableFrictionStateMachine = false;
	EcBoolean enableHoldMode = false;
	EcBoolean enableMCGate = false;
};

struct SampleSmoothingConfig
{
	EcBoolean enabled = false;
	EcRealVector qAlpha;
	EcRealVector dqAlpha;
	EcRealVector ddqAlpha;
};

struct RuntimeValidationConfig
{
	EcBoolean enableFiniteCheck = true;
	EcBoolean enableRadianRangeCheck = true;
	EcBoolean enableGravityNormCheck = true;
	EcReal maxAbsQForRadianCheck = 6.2831853071795862;
	EcReal gravityNormExpected = 9.81;
	EcReal gravityNormTolerance = 1.5;
};

struct DdqClampConfig
{
	EcBoolean enabled = false;
	EcRealVector ddqLimit;
};

struct FrictionStateConfig
{
	EcBoolean enabled = false;
	EcRealVector vOff;
	EcRealVector vOn;
	EcRealVector aOff;
	EcBoolean enableHysteresis = true;
	EcBoolean enableSmoothSign = false;
	EcRealVector smoothVelocity;
	EcBoolean enableHoldMode = false;
	EcRealVector holdBias;
};

struct MCGateConfig
{
	EcBoolean enabled = false;
	EcReal staticWM = 0.0;
	EcReal staticWC = 0.0;
	EcReal transitionWM = 0.0;
	EcReal transitionWC = 0.0;
	EcReal dynamicWM = 1.0;
	EcReal dynamicWC = 1.0;
};

struct RuntimeDiagnostics
{
	EcRealVector q_raw;
	EcRealVector dq_raw;
	EcRealVector ddq_raw;
	EcRealVector q_used;
	EcRealVector dq_used;
	EcRealVector ddq_used;
	EcRealVector tau_M_raw;
	EcRealVector tau_C_raw;
	EcRealVector tau_G;
	EcRealVector tau_F_viscous;
	EcRealVector tau_F_coulomb;
	EcRealVector tau_F_hold;
	EcRealVector tau_F_total;
	EcRealVector tau_M_used;
	EcRealVector tau_C_used;
	EcRealVector tau_total;
	EcRealVector friction_sign;
	EcRealVector hold_indicator;
	EcRealVector motion_state;
	EcRealVector wM;
	EcRealVector wC;
	EcRealVector validation_status;
};

class sevendofDynamics : public dynamicsBase
{
public:
	sevendofDynamics();
	virtual ~sevendofDynamics();

	virtual void setRobotDHParameters
	(
		const EcRealVector& kinematcisParam
	);

	virtual void setGravityVector
	(
		const EcReal gx, const EcReal gy, const EcReal gz
	);

	virtual void calculateGravityJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	virtual EcBoolean calculateEstimateJointToqrues
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

	void setRuntimeTorqueMode
	(
		const EcInt32 mode
	);

	void setRuntimeNoTimeConfig
	(
		const RuntimeNoTimeConfig& config
	);

	void setSampleSmoothingConfig
	(
		const SampleSmoothingConfig& config
	);

	void setRuntimeValidationConfig
	(
		const RuntimeValidationConfig& config
	);

	void setDdqClampConfig
	(
		const DdqClampConfig& config
	);

	void setFrictionStateConfig
	(
		const FrictionStateConfig& config
	);

	void setMCGateConfig
	(
		const MCGateConfig& config
	);

	void resetRuntimeRobustState
	(
	);

	void getLastRuntimeDiagnostics
	(
		RuntimeDiagnostics& diagnostics
	) const;

	void getLastTorqueComponents
	(
		EcRealVector& tauM,
		EcRealVector& tauC,
		EcRealVector& tauG,
		EcRealVector& tauF,
		EcRealVector& tauTotal
	) const;

	void getLastRuntimeSignals
	(
		EcRealVector& qUsed,
		EcRealVector& dqUsed,
		EcRealVector& ddqUsed,
		EcRealVector& frictionSign,
		EcRealVector& motionState
	) const;

	void setUseExternalRuntimeParms
	(
		const EcBoolean useExternalParms
	);

	void setUseInternalPayloadRuntimeParms
	(
		const EcBoolean useInternalPayloadParms
	);

	void setPayloadRuntimeMassAndCom
	(
		const EcReal mass,
		const EcRealVector& com
	);

	void clearPayloadRuntimeOverride
	(
	);

	void computeRigidTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeRigidTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	) const;

	void computeMassTorque
	(
		const EcRealVector& q,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeMassTorque
	(
		const EcRealVector& q,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	) const;

	void computeCoriolisTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		EcRealVector& tau
	) const;

	void computeCoriolisTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& parms,
		EcRealVector& tau
	) const;

	void computeGravityAxisTorques
	(
		const EcRealVector& q,
		EcRealVector& tauGxUnit,
		EcRealVector& tauGyUnit,
		EcRealVector& tauGzUnit
	) const;

	void computeGravityAxisTorques
	(
		const EcRealVector& q,
		const EcRealVector& parms,
		EcRealVector& tauGxUnit,
		EcRealVector& tauGyUnit,
		EcRealVector& tauGzUnit
	) const;

	void computeFrictionTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeFrictionTorque
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	) const;

	void computeInverseDynamics
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		EcRealVector& tau
	) const;

	void computeInverseDynamics
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	) const;

	virtual void calculateMomentumEstimatedJointTorques
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);

private:
	static const EcSizeT kNumJoints = 7;
	static const EcSizeT kRigidParamsPerJoint = 10;
	static const EcSizeT kRuntimeParamsPerJoint = 13;
	EcSizeT m_NumJoints;
	EcReal m_gx;
	EcReal m_gy;
	EcReal m_gz;
	EcBoolean m_useExternalRuntimeParms;
	EcBoolean m_useInternalPayloadRuntimeParms;
	EcBoolean m_hasInternalPayloadOverride;
	EcReal m_payloadMass;
	EcRealVector m_payloadCom;
	EcRealVector m_internalPayloadParms;
	EcRealVector m_zeros;
	EcRealVector m_defaultParms;
	EcInt32 m_runtimeTorqueMode;
	RuntimeNoTimeConfig m_runtimeNoTimeConfig;
	SampleSmoothingConfig m_sampleSmoothingConfig;
	RuntimeValidationConfig m_runtimeValidationConfig;
	DdqClampConfig m_ddqClampConfig;
	FrictionStateConfig m_frictionStateConfig;
	MCGateConfig m_mcGateConfig;
	RuntimeDiagnostics m_lastDiagnostics;
	EcRealVector m_qUsed;
	EcRealVector m_dqUsed;
	EcRealVector m_ddqUsed;
	EcRealVector m_qPrev;
	EcRealVector m_dqPrev;
	EcRealVector m_ddqPrev;
	EcRealVector m_tauM;
	EcRealVector m_tauC;
	EcRealVector m_tauG;
	EcRealVector m_tauF;
	EcRealVector m_tauTotal;
	EcRealVector m_tauFViscous;
	EcRealVector m_tauFCoulomb;
	EcRealVector m_tauFHold;
	EcRealVector m_frictionSign;
	EcRealVector m_holdIndicator;
	EcRealVector m_motionState;
	EcRealVector m_validationStatus;
	EcBoolean m_hasRobustStateInitialized;


	bool hasValidRuntimeParms(const EcRealVector& parms) const;
	bool hasValidPayloadCom(const EcRealVector& com) const;
	bool shouldUseRuntimeParms(const EcRealVector& parms) const;
	void rebuildInternalPayloadRuntimeParms();
	const EcRealVector& activeRuntimeParms(const EcRealVector& parms) const;
	EcReal configValue
	(
		const EcRealVector& values,
		const EcSizeT index,
		const EcReal defaultValue
	) const;
	void clearLastRuntimeDiagnostics(const EcBoolean validationOk);
	void updateMotionStateNoTime();
	EcBoolean validateRuntimeInputNoTime
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);
	EcBoolean calculateEstimateJointToqruesLegacyInternal
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);
	EcBoolean calculateEstimateJointToqruesRobustNoTimeInternal
	(
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcRealVector& tau
	);
	void computeFrictionTorqueRobustNoTimeInternal
	(
		const EcRealVector& parms,
		EcRealVector& tau
	);

	void computeTorqueFromRegressor
	(
		const double* regressor,
		const EcRealVector& q,
		const EcRealVector& dq,
		const EcRealVector& ddq,
		const EcRealVector& parms,
		EcBoolean includeMotorInertia,
		EcBoolean includeFriction,
		EcRealVector& tau
	) const;
};
