"""
Generate controller-side inverse-dynamics code from identified parameters.

This module uses `pinocchio.casadi` to build the symbolic joint-torque
regressor, substitutes the latest identified parameter vector, and asks CasADi
to emit plain C code. The generated file is intended as the bridge from the
Python identification pipeline to embedded/controller projects.
"""

from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path
import re
from typing import Any

import numpy as np

from load_model import pin
from runtime_dynamics import GravityConfig, InertialParameterVector, PayloadMode


@contextmanager
def _pushd(path: Path):
    import os

    previous = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


def _metadata_comment_lines(metadata: dict[str, Any] | None) -> list[str]:
    if not metadata:
        return []
    lines = []
    for key, value in metadata.items():
        if value is not None:
            lines.append(f"// {key}: {value}")
    return lines


def _is_generated_project_file(path: Path) -> bool:
    """
    判断文件是否属于本项目导出的动力学生成物。

    这里只清理 output 根目录下由本导出器生成的 `.h/.cpp/.inc`，
    避免误删用户手写代码或测试支架。
    """
    if path.suffix not in {".h", ".cpp", ".inc"}:
        return False
    if not path.is_file():
        return False
    try:
        first_lines = path.read_text(encoding="utf-8").splitlines()[:3]
    except UnicodeDecodeError:
        return False
    joined = "\n".join(first_lines)
    return "Auto-generated by dynamic_regress/run_pipeline.py." in joined


def _clear_stale_generated_project_files(
    output_dir: Path,
    *,
    keep_paths: set[Path],
) -> None:
    removed = []
    for candidate in output_dir.iterdir():
        if candidate in keep_paths or candidate.name == ".codegen_tmp":
            continue
        if _is_generated_project_file(candidate):
            candidate.unlink()
            removed.append(candidate.name)
    if removed:
        print(
            "Cleared stale generated dynamics file(s): "
            + ", ".join(sorted(removed))
        )


def _write_project_header(
    header_path: Path,
    class_name: str,
    num_joints: int,
    generation_metadata: dict[str, Any] | None = None,
) -> None:
    header_path.write_text(
        "\n".join(
            [
                "// Auto-generated by dynamic_regress/run_pipeline.py.",
                "// RTOSAlgorithm-style wrapper for the identified Pinocchio/CasADi dynamics.",
                *_metadata_comment_lines(generation_metadata),
                "#pragma once",
                "",
                '#include "hansTypes.h"',
                '#include "dynamicsBase.h"',
                "",
                "using namespace KDL;",
                "",
                f"class {class_name} : public dynamicsBase",
                "{",
                "public:",
                f"\t{class_name}();",
                f"\tvirtual ~{class_name}();",
                "",
                "\tvirtual void setRobotDHParameters",
                "\t(",
                "\t\tconst EcRealVector& kinematcisParam",
                "\t);",
                "",
                "\tvirtual void setGravityVector",
                "\t(",
                "\t\tconst EcReal gx, const EcReal gy, const EcReal gz",
                "\t);",
                "",
                "\tvirtual void calculateGravityJointTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t);",
                "",
                "\tvirtual EcBoolean calculateEstimateJointToqrues",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t);",
                "",
                "\tvoid computeRigidTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeMassTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeCoriolisTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeGravityAxisTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tEcRealVector& tauGxUnit,",
                "\t\tEcRealVector& tauGyUnit,",
                "\t\tEcRealVector& tauGzUnit",
                "\t) const;",
                "",
                "\tvoid computeFrictionTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeInverseDynamics",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvirtual void calculateMomentumEstimatedJointTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t);",
                "",
                "private:",
                f"\tstatic const EcSizeT kNumJoints = {num_joints};",
                "\tEcSizeT m_NumJoints;",
                "\tEcReal m_gx;",
                "\tEcReal m_gy;",
                "\tEcReal m_gz;",
                "\tEcRealVector m_zeros;",
                "};",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_project_cpp(
    cpp_path: Path,
    class_name: str,
    num_joints: int,
    gravity_vector: np.ndarray,
    generated_core_code: str,
    generation_metadata: dict[str, Any] | None = None,
) -> None:
    header_name = cpp_path.with_suffix(".h").name

    cpp_path.write_text(
        "\n".join(
            [
                "// Auto-generated by dynamic_regress/run_pipeline.py.",
                "// The public interface follows RTOSAlgorithm dynamics classes.",
                "// The expanded Pinocchio/CasADi formula is embedded below.",
                *_metadata_comment_lines(generation_metadata),
                "",
                f'#include "{header_name}"',
                "",
                "// -----------------------------------------------------------------------------",
                "// Generated inverse-dynamics core",
                "// -----------------------------------------------------------------------------",
                generated_core_code,
                "// -----------------------------------------------------------------------------",
                "// RTOSAlgorithm-style class implementation",
                "// -----------------------------------------------------------------------------",
                "",
                f"{class_name}::{class_name}()",
                "{",
                f"\tm_NumJoints = {num_joints};",
                f"\tm_gx = {float(gravity_vector[0]):.17g};",
                f"\tm_gy = {float(gravity_vector[1]):.17g};",
                f"\tm_gz = {float(gravity_vector[2]):.17g};",
                "\tm_zeros.assign(m_NumJoints, 0.0);",
                "}",
                "",
                f"{class_name}::~{class_name}()",
                "{",
                "}",
                "",
                f"void {class_name}::setRobotDHParameters",
                "(",
                "\tconst EcRealVector& kinematcisParam",
                ")",
                "{",
                "\t// Geometry is fixed by the URDF used during code generation.",
                "\t// Keep this method for compatibility with dynamicsBase callers.",
                "\t(void)kinematcisParam;",
                "}",
                "",
                f"void {class_name}::setGravityVector",
                "(",
                "\tconst EcReal gx, const EcReal gy, const EcReal gz",
                ")",
                "{",
                "\tm_gx = gx;",
                "\tm_gy = gy;",
                "\tm_gz = gz;",
                "}",
                "",
                f"void {class_name}::calculateGravityJointTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ")",
                "{",
                "\t(void)parms;",
                "\tif (q.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tconst double gravity[3] = {m_gx, m_gy, m_gz};",
                "\tcalculateIdentifiedGravityTorqueCore(q.data(), gravity, tau.data());",
                "}",
                "",
                f"void {class_name}::computeRigidTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tconst double gravity[3] = {m_gx, m_gy, m_gz};",
                "\tcalculateIdentifiedRigidDynamicsCore(q.data(), dq.data(), ddq.data(), gravity, tau.data());",
                "}",
                "",
                f"void {class_name}::computeMassTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tcalculateIdentifiedMassTorqueCore(q.data(), ddq.data(), tau.data());",
                "}",
                "",
                f"void {class_name}::computeCoriolisTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tcalculateIdentifiedCoriolisTorqueCore(q.data(), dq.data(), tau.data());",
                "}",
                "",
                f"void {class_name}::computeGravityAxisTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tEcRealVector& tauGxUnit,",
                "\tEcRealVector& tauGyUnit,",
                "\tEcRealVector& tauGzUnit",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tauGxUnit.size() != m_NumJoints)",
                "\t{",
                "\t\ttauGxUnit.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tif (tauGyUnit.size() != m_NumJoints)",
                "\t{",
                "\t\ttauGyUnit.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tif (tauGzUnit.size() != m_NumJoints)",
                "\t{",
                "\t\ttauGzUnit.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tcalculateIdentifiedGravityXAxisTorqueCore(q.data(), tauGxUnit.data());",
                "\tcalculateIdentifiedGravityYAxisTorqueCore(q.data(), tauGyUnit.data());",
                "\tcalculateIdentifiedGravityZAxisTorqueCore(q.data(), tauGzUnit.data());",
                "}",
                "",
                f"void {class_name}::computeFrictionTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tEcRealVector total(m_NumJoints, 0.0);",
                "\tEcRealVector rigid(m_NumJoints, 0.0);",
                "\tcomputeInverseDynamics(q, dq, ddq, total);",
                "\tcomputeRigidTorque(q, dq, ddq, rigid);",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)",
                "\t{",
                "\t\ttau[idx] = total[idx] - rigid[idx];",
                "\t}",
                "}",
                "",
                f"void {class_name}::computeInverseDynamics",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tconst double gravity[3] = {m_gx, m_gy, m_gz};",
                "\tcalculateIdentifiedInverseDynamicsCore(q.data(), dq.data(), ddq.data(), gravity, tau.data());",
                "}",
                "",
                f"EcBoolean {class_name}::calculateEstimateJointToqrues",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ")",
                "{",
                "\t(void)parms;  // Identified parameters are baked into the generated formula.",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn false;",
                "\t}",
                "\tcomputeInverseDynamics(q, dq, ddq, tau);",
                "\treturn true;",
                "}",
                "",
                f"void {class_name}::calculateMomentumEstimatedJointTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ")",
                "{",
                "\t(void)parms;",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "",
                "\tcalculateIdentifiedZeroGravityRigidTorqueCore(q.data(), dq.data(), ddq.data(), tau.data());",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _extract_generated_function(
    source: str,
    function_name: str,
    replacement_signature: str,
    arg_names: list[str],
) -> str:
    marker = f"static int {function_name}("
    start = source.index(marker)
    body_start = source.index("{", start)
    depth = 0
    end = body_start
    for index in range(body_start, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                end = index + 1
                break
    body = source[body_start + 1:end - 1]

    replacements = {
        r"if \(res\[0\]!=0\) res\[0\]\[(\d+)\]=([^;]+);": r"tau[\1] = \2;",
    }
    for arg_index, arg_name in enumerate(arg_names):
        replacements[rf"arg\[{arg_index}\]\? arg\[{arg_index}\]\[(\d+)\] : 0"] = rf"{arg_name}[\1]"
    for pattern, replacement in replacements.items():
        body = re.sub(pattern, replacement, body)
    body = body.replace("  return 0;\n", "")
    return replacement_signature + " {" + body + "\n}\n"


def _make_direct_core_code(generated_source: str) -> str:
    full_core = _extract_generated_function(
        generated_source,
        "casadi_f0",
        "static void calculateIdentifiedInverseDynamicsCore("
        "const double* q, const double* dq, const double* ddq, const double* gravity, double* tau)",
        ["q", "dq", "ddq", "gravity"],
    )
    rigid_core = _extract_generated_function(
        generated_source,
        "casadi_f1",
        "static void calculateIdentifiedRigidDynamicsCore("
        "const double* q, const double* dq, const double* ddq, const double* gravity, double* tau)",
        ["q", "dq", "ddq", "gravity"],
    )
    gravity_core = _extract_generated_function(
        generated_source,
        "casadi_f2",
        "static void calculateIdentifiedGravityTorqueCore("
        "const double* q, const double* gravity, double* tau)",
        ["q", "gravity"],
    )
    zero_gravity_rigid_core = _extract_generated_function(
        generated_source,
        "casadi_f3",
        "static void calculateIdentifiedZeroGravityRigidTorqueCore("
        "const double* q, const double* dq, const double* ddq, double* tau)",
        ["q", "dq", "ddq"],
    )
    mass_core = _extract_generated_function(
        generated_source,
        "casadi_f4",
        "static void calculateIdentifiedMassTorqueCore("
        "const double* q, const double* ddq, double* tau)",
        ["q", "ddq"],
    )
    coriolis_core = _extract_generated_function(
        generated_source,
        "casadi_f5",
        "static void calculateIdentifiedCoriolisTorqueCore("
        "const double* q, const double* dq, double* tau)",
        ["q", "dq"],
    )
    gravity_x_core = _extract_generated_function(
        generated_source,
        "casadi_f6",
        "static void calculateIdentifiedGravityXAxisTorqueCore("
        "const double* q, double* tau)",
        ["q"],
    )
    gravity_y_core = _extract_generated_function(
        generated_source,
        "casadi_f7",
        "static void calculateIdentifiedGravityYAxisTorqueCore("
        "const double* q, double* tau)",
        ["q"],
    )
    gravity_z_core = _extract_generated_function(
        generated_source,
        "casadi_f8",
        "static void calculateIdentifiedGravityZAxisTorqueCore("
        "const double* q, double* tau)",
        ["q"],
    )
    return "\n".join(
        [
            "#include <math.h>",
            "",
            "static double signWithZero(double value)",
            "{",
            "\t// Match the deadzone-aware Coulomb term used during identification.",
            "\tconst double deadzone = 1e-4;",
            "\treturn value < -deadzone ? -1.0 : value > deadzone ? 1.0 : 0.0;",
            "}",
            "",
            "static double square(double value)",
            "{",
            "\treturn value * value;",
            "}",
            "",
            full_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            rigid_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            zero_gravity_rigid_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            mass_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            coriolis_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_x_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_y_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_z_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
        ]
    )


def _format_double(value: float) -> str:
    return f"{float(value):.17g}"


def _format_c_array(values: list[float] | np.ndarray, *, indent: str = "\t") -> str:
    numbers = [_format_double(value) for value in values]
    if not numbers:
        return "{}"
    rows = []
    for start in range(0, len(numbers), 6):
        rows.append(indent + ", ".join(numbers[start:start + 6]))
    return "{\n" + ",\n".join(rows) + "\n}"


def _format_c_matrix(values: list[list[float]] | np.ndarray) -> str:
    matrix = np.asarray(values, dtype=float)
    rows = []
    for row in matrix:
        rows.append("\t{" + ", ".join(_format_double(value) for value in row) + "}")
    return "{\n" + ",\n".join(rows) + "\n}"


def _feature_expression(feature_name: str, num_joints: int) -> str:
    one_joint_patterns = [
        (r"^q_(\d+)$", "q[{idx}]"),
        (r"^dq_(\d+)$", "dq[{idx}]"),
        (r"^ddq_(\d+)$", "ddq[{idx}]"),
        (r"^abs_dq_(\d+)$", "fabs(dq[{idx}])"),
        (r"^abs_ddq_(\d+)$", "fabs(ddq[{idx}])"),
        (r"^q_dq_prod_(\d+)$", "q[{idx}] * dq[{idx}]"),
        (r"^sin_q_(\d+)$", "sin(q[{idx}])"),
        (r"^cos_q_(\d+)$", "cos(q[{idx}])"),
    ]
    for pattern, expression_template in one_joint_patterns:
        match = re.match(pattern, feature_name)
        if match:
            joint_index = int(match.group(1)) - 1
            if joint_index < 0 or joint_index >= num_joints:
                raise ValueError(f"Feature {feature_name!r} references joint outside 1..{num_joints}.")
            return expression_template.format(idx=joint_index)

    match = re.match(r"^dq_pair_(\d+)_(\d+)$", feature_name)
    if match:
        first = int(match.group(1)) - 1
        second = int(match.group(2)) - 1
        if first < 0 or second < 0 or first >= num_joints or second >= num_joints:
            raise ValueError(f"Feature {feature_name!r} references joint outside 1..{num_joints}.")
        return f"dq[{first}] * dq[{second}]"

    if feature_name == "motion_magnitude":
        terms = " + ".join(f"dq[{joint_idx}] * dq[{joint_idx}]" for joint_idx in range(num_joints))
        return f"sqrt({terms})"

    raise ValueError(f"Unsupported MLP feature {feature_name!r}; cannot export C++ code.")


def _make_mlp_core_code(mlp_state: dict[str, Any], num_joints: int) -> str:
    feature_cols = list(mlp_state["feature_cols"])
    x_mean = np.asarray(mlp_state["x_mean"], dtype=float)
    x_scale = np.asarray(mlp_state["x_scale"], dtype=float)
    y_mean = np.asarray(mlp_state["y_mean"], dtype=float)
    y_scale = np.asarray(mlp_state["y_scale"], dtype=float)
    coefs = [np.asarray(coef, dtype=float) for coef in mlp_state["coefs"]]
    intercepts = [np.asarray(bias, dtype=float) for bias in mlp_state["intercepts"]]

    if mlp_state.get("activation") != "relu":
        raise ValueError("Only ReLU MLP compensation can be exported.")
    if len(coefs) != len(intercepts):
        raise ValueError("MLP coefficient/intercept layer count mismatch.")
    if len(feature_cols) != x_mean.size or len(feature_cols) != x_scale.size:
        raise ValueError("MLP feature column count does not match input scaler size.")
    if y_mean.size != num_joints or y_scale.size != num_joints:
        raise ValueError("MLP output scaler size does not match robot joint count.")
    if not coefs or coefs[-1].shape[1] != num_joints:
        raise ValueError("MLP output dimension does not match robot joint count.")
    if coefs[0].shape[0] != len(feature_cols):
        raise ValueError("MLP first layer input dimension does not match feature count.")

    layer_dims = [coefs[0].shape[0]]
    for layer_idx, coef in enumerate(coefs):
        if coef.shape[0] != layer_dims[-1]:
            raise ValueError(f"MLP layer {layer_idx} input dimension mismatch.")
        if intercepts[layer_idx].shape[0] != coef.shape[1]:
            raise ValueError(f"MLP layer {layer_idx} bias dimension mismatch.")
        layer_dims.append(coef.shape[1])

    lines = [
        f"static const int kMlpInputDim = {len(feature_cols)};",
        f"static const int kMlpOutputDim = {num_joints};",
    ]
    for layer_idx, dim in enumerate(layer_dims[1:]):
        lines.append(f"static const int kMlpLayer{layer_idx}Dim = {dim};")
    lines.extend(
        [
            "",
            f"static const double kMlpXMean[kMlpInputDim] = {_format_c_array(x_mean)};",
            f"static const double kMlpXScale[kMlpInputDim] = {_format_c_array(x_scale)};",
            f"static const double kMlpYMean[kMlpOutputDim] = {_format_c_array(y_mean)};",
            f"static const double kMlpYScale[kMlpOutputDim] = {_format_c_array(y_scale)};",
        ]
    )
    for layer_idx, (coef, bias) in enumerate(zip(coefs, intercepts)):
        input_dim = "kMlpInputDim" if layer_idx == 0 else f"kMlpLayer{layer_idx - 1}Dim"
        output_dim = "kMlpOutputDim" if layer_idx == len(coefs) - 1 else f"kMlpLayer{layer_idx}Dim"
        lines.extend(
            [
                "",
                f"static const double kMlpW{layer_idx}[{input_dim}][{output_dim}] = {_format_c_matrix(coef)};",
                f"static const double kMlpB{layer_idx}[{output_dim}] = {_format_c_array(bias)};",
            ]
        )

    lines.extend(
        [
            "",
            "static double relu(double value)",
            "{",
            "\treturn value > 0.0 ? value : 0.0;",
            "}",
            "",
            "static void calculateMlpResidualCompensationCore(",
            "\tconst double* q, const double* dq, const double* ddq, double* residual)",
            "{",
            "\tdouble features[kMlpInputDim];",
        ]
    )
    for feature_idx, feature_name in enumerate(feature_cols):
        lines.append(f"\tfeatures[{feature_idx}] = {_feature_expression(feature_name, num_joints)};")

    lines.extend(
        [
            "\tdouble h0[kMlpLayer0Dim];",
            "\tfor (int outIdx = 0; outIdx < kMlpLayer0Dim; ++outIdx)",
            "\t{",
            "\t\tdouble value = kMlpB0[outIdx];",
            "\t\tfor (int inIdx = 0; inIdx < kMlpInputDim; ++inIdx)",
            "\t\t{",
            "\t\t\tconst double normalized = (features[inIdx] - kMlpXMean[inIdx]) / kMlpXScale[inIdx];",
            "\t\t\tvalue += normalized * kMlpW0[inIdx][outIdx];",
            "\t\t}",
            "\t\th0[outIdx] = relu(value);",
            "\t}",
        ]
    )

    for layer_idx in range(1, len(coefs) - 1):
        prev = f"h{layer_idx - 1}"
        current = f"h{layer_idx}"
        prev_dim = f"kMlpLayer{layer_idx - 1}Dim"
        current_dim = f"kMlpLayer{layer_idx}Dim"
        lines.extend(
            [
                f"\tdouble {current}[{current_dim}];",
                f"\tfor (int outIdx = 0; outIdx < {current_dim}; ++outIdx)",
                "\t{",
                f"\t\tdouble value = kMlpB{layer_idx}[outIdx];",
                f"\t\tfor (int inIdx = 0; inIdx < {prev_dim}; ++inIdx)",
                "\t\t{",
                f"\t\t\tvalue += {prev}[inIdx] * kMlpW{layer_idx}[inIdx][outIdx];",
                "\t\t}",
                f"\t\t{current}[outIdx] = relu(value);",
                "\t}",
            ]
        )

    output_layer_idx = len(coefs) - 1
    prev = f"h{output_layer_idx - 1}"
    prev_dim = f"kMlpLayer{output_layer_idx - 1}Dim"
    lines.extend(
        [
            "\tfor (int outIdx = 0; outIdx < kMlpOutputDim; ++outIdx)",
            "\t{",
            f"\t\tdouble value = kMlpB{output_layer_idx}[outIdx];",
            f"\t\tfor (int inIdx = 0; inIdx < {prev_dim}; ++inIdx)",
            "\t\t{",
            f"\t\t\tvalue += {prev}[inIdx] * kMlpW{output_layer_idx}[inIdx][outIdx];",
            "\t\t}",
            "\t\tresidual[outIdx] = value * kMlpYScale[outIdx] + kMlpYMean[outIdx];",
            "\t}",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def export_identified_inverse_dynamics_cpp(
    *,
    robot_model,
    result: dict,
    urdf_path: Path,
    output_dir: Path,
    result_stem: str,
    mlp_compensator=None,
    generation_metadata: dict[str, Any] | None = None,
    class_name: str = "identifiedDynamics",
    parameter_vector: InertialParameterVector | None = None,
    gravity_config: GravityConfig | str | np.ndarray | list[float] | None = None,
    payload_model=None,
    payload_mode: str | PayloadMode = PayloadMode.NONE,
    payload_frame_transform: np.ndarray | None = None,
) -> dict[str, Path]:
    """
    Export identified inverse-dynamics code into `output_dir`.

    Parameters
    ----------
    robot_model
        The loaded robot model whose Pinocchio model carries the chosen gravity.
    result : dict
        Identification result containing `theta_hat_full`.
    urdf_path : Path
        Kept for API clarity and metadata symmetry with the caller.
    output_dir : Path
        Destination directory.
    result_stem : str
        Usually `real` or `synthetic`.
    mlp_compensator
        当前阶段保留该参数仅为了 API 兼容；导出链默认忽略残差补偿，只生成纯物理模型。
    generation_metadata
        Metadata written into the generated files as comments. This is where
        timestamp/source/mode information belongs, while filenames stay stable.
    class_name : str
        Stable RTOSAlgorithm-side class name to generate.

    Returns
    -------
    dict[str, Path]
        Paths for the generated C source, C header, and C++ wrapper.
    """
    del urdf_path  # Pinocchio model is already built and gravity-configured by the caller.

    if pin is None:
        raise RuntimeError("Pinocchio is not available; cannot generate inverse-dynamics code.")

    try:
        import casadi as ca
        import pinocchio.casadi as cpin
    except ImportError as exc:
        raise RuntimeError(
            "CasADi and pinocchio.casadi are required. Run this pipeline in the "
            "`pinocchio_py` conda environment."
        ) from exc

    output_dir.mkdir(parents=True, exist_ok=True)
    temp_dir = output_dir / ".codegen_tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    num_joints = int(robot_model.num_joints)
    effective_parameter_vector = (
        parameter_vector.copy()
        if parameter_vector is not None
        else InertialParameterVector.from_identification_result(result, num_joints)
    )
    effective_payload_mode = PayloadMode.from_value(
        payload_mode.value if isinstance(payload_mode, PayloadMode) else payload_mode
    )
    if payload_model is not None and effective_payload_mode == PayloadMode.LUMPED_LAST_LINK:
        effective_parameter_vector.add_to_link(
            num_joints - 1,
            payload_model.to_inertial_parameter_delta(frame_transform=payload_frame_transform),
        )
    elif payload_model is not None and effective_payload_mode == PayloadMode.EXTERNAL_WRENCH:
        raise NotImplementedError(
            "C++ export currently supports payload_mode='lumped_last_link' only. "
            "Use the Python runtime model for external-wrench payload compensation."
        )

    theta_full = np.asarray(effective_parameter_vector.to_theta_full(with_friction=True), dtype=float)
    expected_size = 12 * num_joints
    if theta_full.shape != (expected_size,):
        raise ValueError(f"Expected theta_hat_full length {expected_size}, got {theta_full.shape[0]}.")

    num_rigid_params = 10 * num_joints
    theta_rigid = ca.DM(theta_full[:num_rigid_params])
    viscous = theta_full[num_rigid_params:num_rigid_params + num_joints]
    coulomb = theta_full[num_rigid_params + num_joints:]

    cmodel = cpin.Model(robot_model.pinocchio_model)
    cdata = cmodel.createData()

    q = ca.SX.sym("q", num_joints)
    dq = ca.SX.sym("dq", num_joints)
    ddq = ca.SX.sym("ddq", num_joints)

    gravity = ca.SX.sym("gravity", 3)
    gx, gy, gz = gravity[0], gravity[1], gravity[2]

    zero_dq = ca.SX.zeros(num_joints, 1)
    zero_ddq = ca.SX.zeros(num_joints, 1)
    zero_gravity = ca.SX.zeros(3, 1)
    gravity_x = ca.vertcat(ca.SX(1.0), ca.SX(0.0), ca.SX(0.0))
    gravity_y = ca.vertcat(ca.SX(0.0), ca.SX(1.0), ca.SX(0.0))
    gravity_z = ca.vertcat(ca.SX(0.0), ca.SX(0.0), ca.SX(1.0))

    cmodel.gravity.linear = zero_gravity
    y_m = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, ddq)
    y_c = cpin.computeJointTorqueRegressor(cmodel, cdata, q, dq, zero_ddq)

    cmodel.gravity.linear = gravity_x
    y_gx = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, zero_ddq)
    cmodel.gravity.linear = gravity_y
    y_gy = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, zero_ddq)
    cmodel.gravity.linear = gravity_z
    y_gz = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, zero_ddq)

    rigid_regressor = y_m + y_c + gx * y_gx + gy * y_gy + gz * y_gz
    gravity_regressor = gx * y_gx + gy * y_gy + gz * y_gz
    zero_gravity_rigid_regressor = y_m + y_c

    rigid_tau = ca.mtimes(rigid_regressor, theta_rigid)
    gravity_tau = ca.mtimes(gravity_regressor, theta_rigid)
    zero_gravity_rigid_tau = ca.mtimes(zero_gravity_rigid_regressor, theta_rigid)
    friction_tau = ca.vertcat(
        *[
            viscous[joint_idx] * dq[joint_idx] + coulomb[joint_idx] * ca.sign(dq[joint_idx])
            for joint_idx in range(num_joints)
        ]
    )
    tau = rigid_tau + friction_tau

    function_name = "identified_inverse_dynamics"
    function = ca.Function(
        function_name,
        [q, dq, ddq, gravity],
        [tau],
        ["q", "dq", "ddq", "gravity"],
        ["tau"],
    )
    rigid_function = ca.Function(
        "identified_inverse_dynamics_rigid",
        [q, dq, ddq, gravity],
        [rigid_tau],
        ["q", "dq", "ddq", "gravity"],
        ["tau"],
    )
    gravity_function = ca.Function(
        "identified_gravity_torques",
        [q, gravity],
        [gravity_tau],
        ["q", "gravity"],
        ["tau"],
    )
    zero_gravity_rigid_function = ca.Function(
        "identified_zero_gravity_rigid_torques",
        [q, dq, ddq],
        [zero_gravity_rigid_tau],
        ["q", "dq", "ddq"],
        ["tau"],
    )
    mass_function = ca.Function(
        "identified_mass_torques",
        [q, ddq],
        [ca.mtimes(y_m, theta_rigid)],
        ["q", "ddq"],
        ["tau"],
    )
    coriolis_function = ca.Function(
        "identified_coriolis_torques",
        [q, dq],
        [ca.mtimes(y_c, theta_rigid)],
        ["q", "dq"],
        ["tau"],
    )
    gravity_x_function = ca.Function(
        "identified_gravity_xaxis_torques",
        [q],
        [ca.mtimes(y_gx, theta_rigid)],
        ["q"],
        ["tau"],
    )
    gravity_y_function = ca.Function(
        "identified_gravity_yaxis_torques",
        [q],
        [ca.mtimes(y_gy, theta_rigid)],
        ["q"],
        ["tau"],
    )
    gravity_z_function = ca.Function(
        "identified_gravity_zaxis_torques",
        [q],
        [ca.mtimes(y_gz, theta_rigid)],
        ["q"],
        ["tau"],
    )

    c_filename = f"identified_inverse_dynamics_{result_stem}_core.c"
    project_header_filename = f"{class_name}.h"
    project_cpp_filename = f"{class_name}.cpp"

    # CasADi's generator validates the raw filename as a C identifier-like name,
    # so generate from inside the output directory instead of passing a path.
    with _pushd(temp_dir):
        codegen = ca.CodeGenerator(c_filename, {"with_header": True})
        codegen.add(function)
        codegen.add(rigid_function)
        codegen.add(gravity_function)
        codegen.add(zero_gravity_rigid_function)
        codegen.add(mass_function)
        codegen.add(coriolis_function)
        codegen.add(gravity_x_function)
        codegen.add(gravity_y_function)
        codegen.add(gravity_z_function)
        codegen.generate()

    generated_core_code = _make_direct_core_code((temp_dir / c_filename).read_text(encoding="utf-8"))
    for temp_file in temp_dir.iterdir():
        temp_file.unlink()
    temp_dir.rmdir()

    del mlp_compensator

    project_header_path = output_dir / project_header_filename
    project_cpp_path = output_dir / project_cpp_filename
    _clear_stale_generated_project_files(
        output_dir,
        keep_paths={project_header_path, project_cpp_path},
    )
    _write_project_header(project_header_path, class_name, num_joints, generation_metadata)
    _write_project_cpp(
        project_cpp_path,
        class_name,
        num_joints,
        np.asarray(GravityConfig.from_any(gravity_config or robot_model.gravity_vector).gravity_vector_base, dtype=float),
        generated_core_code,
        generation_metadata,
    )

    return {
        "project_header": project_header_path,
        "project_cpp": project_cpp_path,
    }
