"""
Generate controller-side inverse-dynamics code from identified parameters.

This module uses `pinocchio.casadi` to build the symbolic joint-torque
regressor, substitutes the latest identified parameter vector, and asks CasADi
to emit plain C code. The generated file is intended as the bridge from the
Python identification pipeline to embedded/controller projects.
"""

from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path
import re
from typing import Any

import numpy as np

from load_model import pin
from runtime_dynamics import GravityConfig, InertialParameterVector, PayloadMode


@contextmanager
def _pushd(path: Path):
    import os

    previous = Path.cwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


def _metadata_comment_lines(metadata: dict[str, Any] | None) -> list[str]:
    if not metadata:
        return []
    lines = []
    for key, value in metadata.items():
        if value is not None:
            lines.append(f"// {key}: {value}")
    return lines


def _is_generated_project_file(path: Path) -> bool:
    """
    判断文件是否属于本项目导出的动力学生成物。

    这里只清理 output 根目录下由本导出器生成的 `.h/.cpp/.inc`，
    避免误删用户手写代码或测试支架。
    """
    if path.suffix not in {".h", ".cpp", ".inc"}:
        return False
    if not path.is_file():
        return False
    try:
        first_lines = path.read_text(encoding="utf-8").splitlines()[:3]
    except UnicodeDecodeError:
        return False
    joined = "\n".join(first_lines)
    return "Auto-generated by dynamic_regress/run_pipeline.py." in joined


def _clear_stale_generated_project_files(
    output_dir: Path,
    *,
    keep_paths: set[Path],
) -> None:
    removed = []
    for candidate in output_dir.iterdir():
        if candidate in keep_paths or candidate.name == ".codegen_tmp":
            continue
        if _is_generated_project_file(candidate):
            candidate.unlink()
            removed.append(candidate.name)
    if removed:
        print(
            "Cleared stale generated dynamics file(s): "
            + ", ".join(sorted(removed))
        )


def _write_project_header(
    header_path: Path,
    class_name: str,
    num_joints: int,
    generation_metadata: dict[str, Any] | None = None,
) -> None:
    header_path.write_text(
        "\n".join(
            [
                "// Auto-generated by dynamic_regress/run_pipeline.py.",
                "// RTOSAlgorithm-style wrapper for the identified Pinocchio/CasADi dynamics.",
                *_metadata_comment_lines(generation_metadata),
                "#pragma once",
                "",
                '#include "hansTypes.h"',
                '#include "dynamicsBase.h"',
                "",
                "using namespace KDL;",
                "",
                f"class {class_name} : public dynamicsBase",
                "{",
                "public:",
                f"\t{class_name}();",
                f"\tvirtual ~{class_name}();",
                "",
                "\tvirtual void setRobotDHParameters",
                "\t(",
                "\t\tconst EcRealVector& kinematcisParam",
                "\t);",
                "",
                "\tvirtual void setGravityVector",
                "\t(",
                "\t\tconst EcReal gx, const EcReal gy, const EcReal gz",
                "\t);",
                "",
                "\tvirtual void calculateGravityJointTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t);",
                "",
                "\tvirtual EcBoolean calculateEstimateJointToqrues",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t);",
                "",
                "\tvoid setUseExternalRuntimeParms",
                "\t(",
                "\t\tconst EcBoolean useExternalParms",
                "\t);",
                "",
                "\tvoid setUseInternalPayloadRuntimeParms",
                "\t(",
                "\t\tconst EcBoolean useInternalPayloadParms",
                "\t);",
                "",
                "\tvoid setPayloadRuntimeMassAndCom",
                "\t(",
                "\t\tconst EcReal mass,",
                "\t\tconst EcRealVector& com",
                "\t);",
                "",
                "\tvoid clearPayloadRuntimeOverride",
                "\t(",
                "\t);",
                "",
                "\tvoid computeRigidTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeRigidTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeMassTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeMassTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeCoriolisTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeCoriolisTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeGravityAxisTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tEcRealVector& tauGxUnit,",
                "\t\tEcRealVector& tauGyUnit,",
                "\t\tEcRealVector& tauGzUnit",
                "\t) const;",
                "",
                "\tvoid computeGravityAxisTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tauGxUnit,",
                "\t\tEcRealVector& tauGyUnit,",
                "\t\tEcRealVector& tauGzUnit",
                "\t) const;",
                "",
                "\tvoid computeFrictionTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeFrictionTorque",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeInverseDynamics",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvoid computeInverseDynamics",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "",
                "\tvirtual void calculateMomentumEstimatedJointTorques",
                "\t(",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcRealVector& tau",
                "\t);",
                "",
                "private:",
                f"\tstatic const EcSizeT kNumJoints = {num_joints};",
                "\tstatic const EcSizeT kRigidParamsPerJoint = 10;",
                "\tstatic const EcSizeT kRuntimeParamsPerJoint = 13;",
                "\tEcSizeT m_NumJoints;",
                "\tEcReal m_gx;",
                "\tEcReal m_gy;",
                "\tEcReal m_gz;",
                "\tEcBoolean m_useExternalRuntimeParms;",
                "\tEcBoolean m_useInternalPayloadRuntimeParms;",
                "\tEcBoolean m_hasInternalPayloadOverride;",
                "\tEcReal m_payloadMass;",
                "\tEcRealVector m_payloadCom;",
                "\tEcRealVector m_internalPayloadParms;",
                "\tEcRealVector m_zeros;",
                "\tEcRealVector m_defaultParms;",
                "",
                "\tbool hasValidRuntimeParms(const EcRealVector& parms) const;",
                "\tbool hasValidPayloadCom(const EcRealVector& com) const;",
                "\tbool shouldUseRuntimeParms(const EcRealVector& parms) const;",
                "\tvoid rebuildInternalPayloadRuntimeParms();",
                "\tconst EcRealVector& activeRuntimeParms(const EcRealVector& parms) const;",
                "\tvoid computeTorqueFromRegressor",
                "\t(",
                "\t\tconst double* regressor,",
                "\t\tconst EcRealVector& q,",
                "\t\tconst EcRealVector& dq,",
                "\t\tconst EcRealVector& ddq,",
                "\t\tconst EcRealVector& parms,",
                "\t\tEcBoolean includeMotorInertia,",
                "\t\tEcBoolean includeFriction,",
                "\t\tEcRealVector& tau",
                "\t) const;",
                "};",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_project_cpp(
    cpp_path: Path,
    class_name: str,
    num_joints: int,
    gravity_vector: np.ndarray,
    default_runtime_parms: np.ndarray,
    generated_core_code: str,
    generation_metadata: dict[str, Any] | None = None,
) -> None:
    header_name = cpp_path.with_suffix(".h").name
    default_runtime_parms_literal = _format_c_array(default_runtime_parms, indent="\t")

    cpp_path.write_text(
        "\n".join(
            [
                "// Auto-generated by dynamic_regress/run_pipeline.py.",
                "// The public interface follows RTOSAlgorithm dynamics classes.",
                "// The expanded Pinocchio/CasADi formula is embedded below.",
                *_metadata_comment_lines(generation_metadata),
                "",
                f'#include "{header_name}"',
                "",
                "namespace",
                "{",
                f"const EcReal kDefaultRuntimeParms[{num_joints * 13}] = {default_runtime_parms_literal};",
                "}  // namespace",
                "",
                "// -----------------------------------------------------------------------------",
                "// Generated inverse-dynamics core",
                "// -----------------------------------------------------------------------------",
                generated_core_code,
                "// -----------------------------------------------------------------------------",
                "// RTOSAlgorithm-style class implementation",
                "// -----------------------------------------------------------------------------",
                "",
                f"{class_name}::{class_name}()",
                "{",
                f"\tm_NumJoints = {num_joints};",
                f"\tm_gx = {float(gravity_vector[0]):.17g};",
                f"\tm_gy = {float(gravity_vector[1]):.17g};",
                f"\tm_gz = {float(gravity_vector[2]):.17g};",
                "\tm_useExternalRuntimeParms = false;",
                "\tm_useInternalPayloadRuntimeParms = false;",
                "\tm_hasInternalPayloadOverride = false;",
                "\tm_payloadMass = 0.0;",
                "\tm_payloadCom.assign(3, 0.0);",
                "\tm_zeros.assign(m_NumJoints, 0.0);",
                "\tm_defaultParms.assign(kDefaultRuntimeParms, kDefaultRuntimeParms + kNumJoints * kRuntimeParamsPerJoint);",
                "\tm_internalPayloadParms = m_defaultParms;",
                "}",
                "",
                f"{class_name}::~{class_name}()",
                "{",
                "}",
                "",
                f"void {class_name}::setRobotDHParameters",
                "(",
                "\tconst EcRealVector& kinematcisParam",
                ")",
                "{",
                "\t// Geometry is fixed by the URDF used during code generation.",
                "\t// Keep this method for compatibility with dynamicsBase callers.",
                "\t(void)kinematcisParam;",
                "}",
                "",
                f"void {class_name}::setGravityVector",
                "(",
                "\tconst EcReal gx, const EcReal gy, const EcReal gz",
                ")",
                "{",
                "\tm_gx = gx;",
                "\tm_gy = gy;",
                "\tm_gz = gz;",
                "}",
                "",
                f"void {class_name}::setUseExternalRuntimeParms",
                "(",
                "\tconst EcBoolean useExternalParms",
                ")",
                "{",
                "\tm_useExternalRuntimeParms = useExternalParms;",
                "}",
                "",
                f"void {class_name}::setUseInternalPayloadRuntimeParms",
                "(",
                "\tconst EcBoolean useInternalPayloadParms",
                ")",
                "{",
                "\tm_useInternalPayloadRuntimeParms = useInternalPayloadParms;",
                "}",
                "",
                f"void {class_name}::setPayloadRuntimeMassAndCom",
                "(",
                "\tconst EcReal mass,",
                "\tconst EcRealVector& com",
                ")",
                "{",
                "\tm_payloadMass = mass;",
                "\tm_payloadCom = com;",
                "\trebuildInternalPayloadRuntimeParms();",
                "}",
                "",
                f"void {class_name}::clearPayloadRuntimeOverride",
                "(",
                ")",
                "{",
                "\tm_payloadMass = 0.0;",
                "\tm_payloadCom.assign(3, 0.0);",
                "\tm_hasInternalPayloadOverride = false;",
                "\tm_internalPayloadParms = m_defaultParms;",
                "}",
                "",
                f"bool {class_name}::hasValidRuntimeParms",
                "(",
                "\tconst EcRealVector& parms",
                ") const",
                "{",
                "\treturn parms.empty() || parms.size() == kNumJoints * kRuntimeParamsPerJoint;",
                "}",
                "",
                f"bool {class_name}::hasValidPayloadCom",
                "(",
                "\tconst EcRealVector& com",
                ") const",
                "{",
                "\treturn com.size() == 3;",
                "}",
                "",
                f"bool {class_name}::shouldUseRuntimeParms",
                "(",
                "\tconst EcRealVector& parms",
                ") const",
                "{",
                "\tif (!parms.empty() && m_useExternalRuntimeParms)",
                "\t{",
                "\t\treturn true;",
                "\t}",
                "\treturn m_useInternalPayloadRuntimeParms && m_hasInternalPayloadOverride;",
                "}",
                "",
                f"void {class_name}::rebuildInternalPayloadRuntimeParms",
                "(",
                ")",
                "{",
                "\tm_internalPayloadParms = m_defaultParms;",
                "\tm_hasInternalPayloadOverride = false;",
                "\tif (m_payloadMass <= 0.0 || !hasValidPayloadCom(m_payloadCom))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tconst EcSizeT lastJointOffset = (kNumJoints - 1) * kRuntimeParamsPerJoint;",
                "\tconst EcReal x = m_payloadCom[0];",
                "\tconst EcReal y = m_payloadCom[1];",
                "\tconst EcReal z = m_payloadCom[2];",
                "\tm_internalPayloadParms[lastJointOffset + 0] += m_payloadMass * (y * y + z * z);",
                "\tm_internalPayloadParms[lastJointOffset + 1] += -m_payloadMass * x * y;",
                "\tm_internalPayloadParms[lastJointOffset + 2] += -m_payloadMass * x * z;",
                "\tm_internalPayloadParms[lastJointOffset + 3] += m_payloadMass * (x * x + z * z);",
                "\tm_internalPayloadParms[lastJointOffset + 4] += -m_payloadMass * y * z;",
                "\tm_internalPayloadParms[lastJointOffset + 5] += m_payloadMass * (x * x + y * y);",
                "\tm_internalPayloadParms[lastJointOffset + 6] += m_payloadMass * x;",
                "\tm_internalPayloadParms[lastJointOffset + 7] += m_payloadMass * y;",
                "\tm_internalPayloadParms[lastJointOffset + 8] += m_payloadMass * z;",
                "\tm_internalPayloadParms[lastJointOffset + 9] += m_payloadMass;",
                "\tm_hasInternalPayloadOverride = true;",
                "}",
                "",
                f"const EcRealVector& {class_name}::activeRuntimeParms",
                "(",
                "\tconst EcRealVector& parms",
                ") const",
                "{",
                "\tif (!parms.empty() && m_useExternalRuntimeParms)",
                "\t{",
                "\t\treturn parms;",
                "\t}",
                "\tif (m_useInternalPayloadRuntimeParms && m_hasInternalPayloadOverride)",
                "\t{",
                "\t\treturn m_internalPayloadParms;",
                "\t}",
                "\treturn m_defaultParms;",
                "}",
                "",
                f"void {class_name}::computeTorqueFromRegressor",
                "(",
                "\tconst double* regressor,",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcBoolean includeMotorInertia,",
                "\tEcBoolean includeFriction,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\t(void)q;",
                "\tconst EcRealVector& activeParms = activeRuntimeParms(parms);",
                "\tdouble thetaRigid[kNumJoints * kRigidParamsPerJoint];",
                "\tfor (EcSizeT jointIdx = 0; jointIdx < kNumJoints; ++jointIdx)",
                "\t{",
                "\t\tconst EcSizeT runtimeOffset = jointIdx * kRuntimeParamsPerJoint;",
                "\t\tconst EcSizeT rigidOffset = jointIdx * kRigidParamsPerJoint;",
                "\t\tthetaRigid[rigidOffset + 0] = activeParms[runtimeOffset + 9];",
                "\t\tthetaRigid[rigidOffset + 1] = activeParms[runtimeOffset + 6];",
                "\t\tthetaRigid[rigidOffset + 2] = activeParms[runtimeOffset + 7];",
                "\t\tthetaRigid[rigidOffset + 3] = activeParms[runtimeOffset + 8];",
                "\t\tthetaRigid[rigidOffset + 4] = activeParms[runtimeOffset + 0];",
                "\t\tthetaRigid[rigidOffset + 5] = activeParms[runtimeOffset + 1];",
                "\t\tthetaRigid[rigidOffset + 6] = activeParms[runtimeOffset + 2];",
                "\t\tthetaRigid[rigidOffset + 7] = activeParms[runtimeOffset + 3];",
                "\t\tthetaRigid[rigidOffset + 8] = activeParms[runtimeOffset + 4];",
                "\t\tthetaRigid[rigidOffset + 9] = activeParms[runtimeOffset + 5];",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tfor (EcSizeT rowIdx = 0; rowIdx < kNumJoints; ++rowIdx)",
                "\t{",
                "\t\tdouble value = 0.0;",
                "\t\tfor (EcSizeT colIdx = 0; colIdx < kNumJoints * kRigidParamsPerJoint; ++colIdx)",
                "\t\t{",
                "\t\t\tvalue += regressor[rowIdx * kNumJoints * kRigidParamsPerJoint + colIdx] * thetaRigid[colIdx];",
                "\t\t}",
                "\t\tif (includeMotorInertia)",
                "\t\t{",
                "\t\t\tvalue += activeParms[rowIdx * kRuntimeParamsPerJoint + 10] * ddq[rowIdx];",
                "\t\t}",
                "\t\tif (includeFriction)",
                "\t\t{",
                "\t\t\tvalue += activeParms[rowIdx * kRuntimeParamsPerJoint + 11] * dq[rowIdx];",
                "\t\t\tvalue += activeParms[rowIdx * kRuntimeParamsPerJoint + 12] * signWithZero(dq[rowIdx]);",
                "\t\t}",
                "\t\ttau[rowIdx] = value;",
                "\t}",
                "}",
                "",
                f"void {class_name}::calculateGravityJointTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ")",
                "{",
                "\tif (q.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tconst double gravity[3] = {m_gx, m_gy, m_gz};",
                "\tdouble regressor[kNumJoints * kNumJoints * kRigidParamsPerJoint];",
                "\tcalculateIdentifiedGravityRegressorRowMajorCore(q.data(), gravity, regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, m_zeros, m_zeros, parms, false, false, tau);",
                "}",
                "",
                f"void {class_name}::computeRigidTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tcomputeRigidTorque(q, dq, ddq, EcRealVector(), tau);",
                "}",
                "",
                f"void {class_name}::computeRigidTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tEcRealVector tauM(m_NumJoints, 0.0);",
                "\tEcRealVector tauC(m_NumJoints, 0.0);",
                "\tEcRealVector tauG(m_NumJoints, 0.0);",
                "\tcomputeMassTorque(q, ddq, parms, tauM);",
                "\tcomputeCoriolisTorque(q, dq, parms, tauC);",
                "\tconst double gravity[3] = {m_gx, m_gy, m_gz};",
                "\tdouble regressor[kNumJoints * kNumJoints * kRigidParamsPerJoint];",
                "\tcalculateIdentifiedGravityRegressorRowMajorCore(q.data(), gravity, regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, m_zeros, m_zeros, parms, false, false, tauG);",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)",
                "\t{",
                "\t\ttau[idx] = tauM[idx] + tauC[idx] + tauG[idx];",
                "\t}",
                "}",
                "",
                f"void {class_name}::computeMassTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tcomputeMassTorque(q, ddq, EcRealVector(), tau);",
                "}",
                "",
                f"void {class_name}::computeMassTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tdouble regressor[kNumJoints * kNumJoints * kRigidParamsPerJoint];",
                "\tcalculateIdentifiedZeroGravityRigidRegressorRowMajorCore(q.data(), m_zeros.data(), ddq.data(), regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, m_zeros, ddq, parms, false, false, tau);",
                "}",
                "",
                f"void {class_name}::computeCoriolisTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tcomputeCoriolisTorque(q, dq, EcRealVector(), tau);",
                "}",
                "",
                f"void {class_name}::computeCoriolisTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tdouble regressor[kNumJoints * kNumJoints * kRigidParamsPerJoint];",
                "\tcalculateIdentifiedZeroGravityRigidRegressorRowMajorCore(q.data(), dq.data(), m_zeros.data(), regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, dq, m_zeros, parms, false, false, tau);",
                "}",
                "",
                f"void {class_name}::computeGravityAxisTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tEcRealVector& tauGxUnit,",
                "\tEcRealVector& tauGyUnit,",
                "\tEcRealVector& tauGzUnit",
                ") const",
                "{",
                "\tcomputeGravityAxisTorques(q, EcRealVector(), tauGxUnit, tauGyUnit, tauGzUnit);",
                "}",
                "",
                f"void {class_name}::computeGravityAxisTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tauGxUnit,",
                "\tEcRealVector& tauGyUnit,",
                "\tEcRealVector& tauGzUnit",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tauGxUnit.size() != m_NumJoints)",
                "\t{",
                "\t\ttauGxUnit.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tif (tauGyUnit.size() != m_NumJoints)",
                "\t{",
                "\t\ttauGyUnit.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tif (tauGzUnit.size() != m_NumJoints)",
                "\t{",
                "\t\ttauGzUnit.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tconst EcReal gxUnit[3] = {1.0, 0.0, 0.0};",
                "\tconst EcReal gyUnit[3] = {0.0, 1.0, 0.0};",
                "\tconst EcReal gzUnit[3] = {0.0, 0.0, 1.0};",
                "\tdouble regressor[kNumJoints * kNumJoints * kRigidParamsPerJoint];",
                "\tcalculateIdentifiedGravityRegressorRowMajorCore(q.data(), gxUnit, regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, m_zeros, m_zeros, parms, false, false, tauGxUnit);",
                "\tcalculateIdentifiedGravityRegressorRowMajorCore(q.data(), gyUnit, regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, m_zeros, m_zeros, parms, false, false, tauGyUnit);",
                "\tcalculateIdentifiedGravityRegressorRowMajorCore(q.data(), gzUnit, regressor);",
                "\tcomputeTorqueFromRegressor(regressor, q, m_zeros, m_zeros, parms, false, false, tauGzUnit);",
                "}",
                "",
                f"void {class_name}::computeFrictionTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tcomputeFrictionTorque(q, dq, ddq, EcRealVector(), tau);",
                "}",
                "",
                f"void {class_name}::computeFrictionTorque",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tconst EcRealVector& activeParms = activeRuntimeParms(parms);",
                "\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)",
                "\t{",
                "\t\tconst EcSizeT runtimeOffset = idx * kRuntimeParamsPerJoint;",
                "\t\ttau[idx] = activeParms[runtimeOffset + 10] * ddq[idx]",
                "\t\t\t+ activeParms[runtimeOffset + 11] * dq[idx]",
                "\t\t\t+ activeParms[runtimeOffset + 12] * signWithZero(dq[idx]);",
                "\t}",
                "}",
                "",
                f"void {class_name}::computeInverseDynamics",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tcomputeInverseDynamics(q, dq, ddq, EcRealVector(), tau);",
                "}",
                "",
                f"void {class_name}::computeInverseDynamics",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ") const",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tEcRealVector tauRigid(m_NumJoints, 0.0);",
                "\tEcRealVector tauFriction(m_NumJoints, 0.0);",
                "\tcomputeRigidTorque(q, dq, ddq, parms, tauRigid);",
                "\tcomputeFrictionTorque(q, dq, ddq, parms, tauFriction);",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)",
                "\t{",
                "\t\ttau[idx] = tauRigid[idx] + tauFriction[idx];",
                "\t}",
                "}",
                "",
                f"EcBoolean {class_name}::calculateEstimateJointToqrues",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ")",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn false;",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn false;",
                "\t}",
                "\tEcRealVector tauM(m_NumJoints, 0.0);",
                "\tEcRealVector tauC(m_NumJoints, 0.0);",
                "\tEcRealVector tauG(m_NumJoints, 0.0);",
                "\tEcRealVector tauF(m_NumJoints, 0.0);",
                "\tcomputeMassTorque(q, ddq, parms, tauM);",
                "\tcomputeCoriolisTorque(q, dq, parms, tauC);",
                "\tcalculateGravityJointTorques(q, parms, tauG);",
                "\tcomputeFrictionTorque(q, dq, ddq, parms, tauF);",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)",
                "\t{",
                "\t\ttau[idx] = tauM[idx] + tauC[idx] + tauG[idx] + tauF[idx];",
                "\t}",
                "\treturn true;",
                "}",
                "",
                f"void {class_name}::calculateMomentumEstimatedJointTorques",
                "(",
                "\tconst EcRealVector& q,",
                "\tconst EcRealVector& dq,",
                "\tconst EcRealVector& ddq,",
                "\tconst EcRealVector& parms,",
                "\tEcRealVector& tau",
                ")",
                "{",
                "\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))",
                "\t{",
                "\t\treturn;",
                "\t}",
                "\tEcRealVector tauM(m_NumJoints, 0.0);",
                "\tEcRealVector tauC(m_NumJoints, 0.0);",
                "\tcomputeMassTorque(q, ddq, parms, tauM);",
                "\tcomputeCoriolisTorque(q, dq, parms, tauC);",
                "\tif (tau.size() != m_NumJoints)",
                "\t{",
                "\t\ttau.assign(m_NumJoints, 0.0);",
                "\t}",
                "\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)",
                "\t{",
                "\t\ttau[idx] = tauM[idx] + tauC[idx];",
                "\t}",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _inject_runtime_robust_header(header_path: Path, class_name: str) -> None:
    source = header_path.read_text(encoding="utf-8")
    prelude = """
enum RuntimeTorqueMode
{
\tLEGACY_RAW = 0,
\tROBUST_NO_TIME = 1,
\tROBUST_TIMED_RESERVED = 2
};

enum MotionState
{
\tSTATIC = 0,
\tMOVING_POSITIVE = 1,
\tMOVING_NEGATIVE = 2,
\tTRANSITION = 3
};

struct RuntimeNoTimeConfig
{
\tEcBoolean enableInputValidation = true;
\tEcBoolean enableSampleSmoothing = false;
\tEcBoolean enableDdqClamp = false;
\tEcBoolean enableFrictionStateMachine = false;
\tEcBoolean enableHoldMode = false;
\tEcBoolean enableMCGate = false;
};

struct SampleSmoothingConfig
{
\tEcBoolean enabled = false;
\tEcRealVector qAlpha;
\tEcRealVector dqAlpha;
\tEcRealVector ddqAlpha;
};

struct RuntimeValidationConfig
{
\tEcBoolean enableFiniteCheck = true;
\tEcBoolean enableRadianRangeCheck = true;
\tEcBoolean enableGravityNormCheck = true;
\tEcReal maxAbsQForRadianCheck = 6.2831853071795862;
\tEcReal gravityNormExpected = 9.81;
\tEcReal gravityNormTolerance = 1.5;
};

struct DdqClampConfig
{
\tEcBoolean enabled = false;
\tEcRealVector ddqLimit;
};

struct FrictionStateConfig
{
\tEcBoolean enabled = false;
\tEcRealVector vOff;
\tEcRealVector vOn;
\tEcRealVector aOff;
\tEcBoolean enableHysteresis = true;
\tEcBoolean enableSmoothSign = false;
\tEcRealVector smoothVelocity;
\tEcBoolean enableHoldMode = false;
\tEcRealVector holdBias;
};

struct MCGateConfig
{
\tEcBoolean enabled = false;
\tEcReal staticWM = 0.0;
\tEcReal staticWC = 0.0;
\tEcReal transitionWM = 0.0;
\tEcReal transitionWC = 0.0;
\tEcReal dynamicWM = 1.0;
\tEcReal dynamicWC = 1.0;
};

struct RuntimeDiagnostics
{
\tEcRealVector q_raw;
\tEcRealVector dq_raw;
\tEcRealVector ddq_raw;
\tEcRealVector q_used;
\tEcRealVector dq_used;
\tEcRealVector ddq_used;
\tEcRealVector tau_M_raw;
\tEcRealVector tau_C_raw;
\tEcRealVector tau_G;
\tEcRealVector tau_F_viscous;
\tEcRealVector tau_F_coulomb;
\tEcRealVector tau_F_hold;
\tEcRealVector tau_F_total;
\tEcRealVector tau_M_used;
\tEcRealVector tau_C_used;
\tEcRealVector tau_total;
\tEcRealVector friction_sign;
\tEcRealVector hold_indicator;
\tEcRealVector motion_state;
\tEcRealVector wM;
\tEcRealVector wC;
\tEcRealVector validation_status;
};

""".lstrip("\n")
    public_methods = """
\tvoid setRuntimeTorqueMode
\t(
\t\tconst EcInt32 mode
\t);

\tvoid setRuntimeNoTimeConfig
\t(
\t\tconst RuntimeNoTimeConfig& config
\t);

\tvoid setSampleSmoothingConfig
\t(
\t\tconst SampleSmoothingConfig& config
\t);

\tvoid setRuntimeValidationConfig
\t(
\t\tconst RuntimeValidationConfig& config
\t);

\tvoid setDdqClampConfig
\t(
\t\tconst DdqClampConfig& config
\t);

\tvoid setFrictionStateConfig
\t(
\t\tconst FrictionStateConfig& config
\t);

\tvoid setMCGateConfig
\t(
\t\tconst MCGateConfig& config
\t);

\tvoid resetRuntimeRobustState
\t(
\t);

\tvoid getLastRuntimeDiagnostics
\t(
\t\tRuntimeDiagnostics& diagnostics
\t) const;

\tvoid getLastTorqueComponents
\t(
\t\tEcRealVector& tauM,
\t\tEcRealVector& tauC,
\t\tEcRealVector& tauG,
\t\tEcRealVector& tauF,
\t\tEcRealVector& tauTotal
\t) const;

\tvoid getLastRuntimeSignals
\t(
\t\tEcRealVector& qUsed,
\t\tEcRealVector& dqUsed,
\t\tEcRealVector& ddqUsed,
\t\tEcRealVector& frictionSign,
\t\tEcRealVector& motionState
\t) const;

""".lstrip("\n")
    private_decls = """
\tEcReal configValue
\t(
\t\tconst EcRealVector& values,
\t\tconst EcSizeT index,
\t\tconst EcReal defaultValue
\t) const;
\tvoid clearLastRuntimeDiagnostics(const EcBoolean validationOk);
\tvoid updateMotionStateNoTime();
\tEcBoolean validateRuntimeInputNoTime
\t(
\t\tconst EcRealVector& q,
\t\tconst EcRealVector& dq,
\t\tconst EcRealVector& ddq,
\t\tconst EcRealVector& parms,
\t\tEcRealVector& tau
\t);
\tEcBoolean calculateEstimateJointToqruesLegacyInternal
\t(
\t\tconst EcRealVector& q,
\t\tconst EcRealVector& dq,
\t\tconst EcRealVector& ddq,
\t\tconst EcRealVector& parms,
\t\tEcRealVector& tau
\t);
\tEcBoolean calculateEstimateJointToqruesRobustNoTimeInternal
\t(
\t\tconst EcRealVector& q,
\t\tconst EcRealVector& dq,
\t\tconst EcRealVector& ddq,
\t\tconst EcRealVector& parms,
\t\tEcRealVector& tau
\t);
\tvoid computeFrictionTorqueRobustNoTimeInternal
\t(
\t\tconst EcRealVector& parms,
\t\tEcRealVector& tau
\t);

""".lstrip("\n")
    member_block = """
\tEcInt32 m_runtimeTorqueMode;
\tRuntimeNoTimeConfig m_runtimeNoTimeConfig;
\tSampleSmoothingConfig m_sampleSmoothingConfig;
\tRuntimeValidationConfig m_runtimeValidationConfig;
\tDdqClampConfig m_ddqClampConfig;
\tFrictionStateConfig m_frictionStateConfig;
\tMCGateConfig m_mcGateConfig;
\tRuntimeDiagnostics m_lastDiagnostics;
\tEcRealVector m_qUsed;
\tEcRealVector m_dqUsed;
\tEcRealVector m_ddqUsed;
\tEcRealVector m_qPrev;
\tEcRealVector m_dqPrev;
\tEcRealVector m_ddqPrev;
\tEcRealVector m_tauM;
\tEcRealVector m_tauC;
\tEcRealVector m_tauG;
\tEcRealVector m_tauF;
\tEcRealVector m_tauTotal;
\tEcRealVector m_tauFViscous;
\tEcRealVector m_tauFCoulomb;
\tEcRealVector m_tauFHold;
\tEcRealVector m_frictionSign;
\tEcRealVector m_holdIndicator;
\tEcRealVector m_motionState;
\tEcRealVector m_validationStatus;
\tEcBoolean m_hasRobustStateInitialized;

""".lstrip("\n")

    source = source.replace("using namespace KDL;\n\n", "using namespace KDL;\n\n" + prelude)
    source = source.replace(
        "\tvoid setUseExternalRuntimeParms\n",
        public_methods + "\tvoid setUseExternalRuntimeParms\n",
    )
    source = source.replace(
        "\tEcRealVector m_defaultParms;\n\n",
        "\tEcRealVector m_defaultParms;\n"
        + member_block
        + "\n",
    )
    source = source.replace(
        "\tconst EcRealVector& activeRuntimeParms(const EcRealVector& parms) const;\n",
        "\tconst EcRealVector& activeRuntimeParms(const EcRealVector& parms) const;\n"
        + private_decls,
    )
    header_path.write_text(source, encoding="utf-8")


def _inject_runtime_robust_cpp(cpp_path: Path, class_name: str) -> None:
    source = cpp_path.read_text(encoding="utf-8")
    ctor_old = (
        f"{class_name}::{class_name}()\n"
        "{\n"
        "\tm_NumJoints = 7;\n"
    )
    source = source.replace(ctor_old, ctor_old)
    source = source.replace(
        "\tm_internalPayloadParms = m_defaultParms;\n}",
        "\tm_internalPayloadParms = m_defaultParms;\n"
        "\tm_runtimeTorqueMode = LEGACY_RAW;\n"
        "\tm_sampleSmoothingConfig.qAlpha.assign(kNumJoints, 1.0);\n"
        "\tm_sampleSmoothingConfig.dqAlpha.assign(kNumJoints, 1.0);\n"
        "\tm_sampleSmoothingConfig.ddqAlpha.assign(kNumJoints, 1.0);\n"
        "\tm_ddqClampConfig.ddqLimit.assign(kNumJoints, 50.0);\n"
        "\tm_frictionStateConfig.vOff.assign(kNumJoints, 0.01);\n"
        "\tm_frictionStateConfig.vOn.assign(kNumJoints, 0.03);\n"
        "\tm_frictionStateConfig.aOff.assign(kNumJoints, 0.2);\n"
        "\tm_frictionStateConfig.smoothVelocity.assign(kNumJoints, 0.02);\n"
        "\tm_frictionStateConfig.holdBias.assign(kNumJoints, 0.0);\n"
        "\tresetRuntimeRobustState();\n}",
    )

    legacy_impl = f"""EcBoolean {class_name}::calculateEstimateJointToqruesLegacyInternal
(
\tconst EcRealVector& q,
\tconst EcRealVector& dq,
\tconst EcRealVector& ddq,
\tconst EcRealVector& parms,
\tEcRealVector& tau
)
{{
\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)
\t{{
\t\treturn false;
\t}}
\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))
\t{{
\t\treturn false;
\t}}
\tEcRealVector tauM(m_NumJoints, 0.0);
\tEcRealVector tauC(m_NumJoints, 0.0);
\tEcRealVector tauG(m_NumJoints, 0.0);
\tEcRealVector tauF(m_NumJoints, 0.0);
\tcomputeMassTorque(q, ddq, parms, tauM);
\tcomputeCoriolisTorque(q, dq, parms, tauC);
\tcalculateGravityJointTorques(q, parms, tauG);
\tcomputeFrictionTorque(q, dq, ddq, parms, tauF);
\tif (tau.size() != m_NumJoints)
\t{{
\t\ttau.assign(m_NumJoints, 0.0);
\t}}
\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t{{
\t\ttau[idx] = tauM[idx] + tauC[idx] + tauG[idx] + tauF[idx];
\t}}
\treturn true;
}}
"""

    dispatch_impl = f"""EcBoolean {class_name}::calculateEstimateJointToqrues
(
\tconst EcRealVector& q,
\tconst EcRealVector& dq,
\tconst EcRealVector& ddq,
\tconst EcRealVector& parms,
\tEcRealVector& tau
)
{{
\tif (m_runtimeTorqueMode == ROBUST_NO_TIME)
\t{{
\t\treturn calculateEstimateJointToqruesRobustNoTimeInternal(q, dq, ddq, parms, tau);
\t}}
\tif (m_runtimeTorqueMode == ROBUST_TIMED_RESERVED)
\t{{
\t\t// Reserved for a future timestamp/dt-aware implementation without changing
\t\t// the shared external virtual function signature.
\t\treturn calculateEstimateJointToqruesLegacyInternal(q, dq, ddq, parms, tau);
\t}}
\treturn calculateEstimateJointToqruesLegacyInternal(q, dq, ddq, parms, tau);
}}
"""

    old_dispatch = f"""EcBoolean {class_name}::calculateEstimateJointToqrues
(
\tconst EcRealVector& q,
\tconst EcRealVector& dq,
\tconst EcRealVector& ddq,
\tconst EcRealVector& parms,
\tEcRealVector& tau
)
{{
\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)
\t{{
\t\treturn false;
\t}}
\tif (!parms.empty() && m_useExternalRuntimeParms && !hasValidRuntimeParms(parms))
\t{{
\t\treturn false;
\t}}
\tEcRealVector tauM(m_NumJoints, 0.0);
\tEcRealVector tauC(m_NumJoints, 0.0);
\tEcRealVector tauG(m_NumJoints, 0.0);
\tEcRealVector tauF(m_NumJoints, 0.0);
\tcomputeMassTorque(q, ddq, parms, tauM);
\tcomputeCoriolisTorque(q, dq, parms, tauC);
\tcalculateGravityJointTorques(q, parms, tauG);
\tcomputeFrictionTorque(q, dq, ddq, parms, tauF);
\tif (tau.size() != m_NumJoints)
\t{{
\t\ttau.assign(m_NumJoints, 0.0);
\t}}
\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t{{
\t\ttau[idx] = tauM[idx] + tauC[idx] + tauG[idx] + tauF[idx];
\t}}
\treturn true;
}}
"""
    source = source.replace(old_dispatch, legacy_impl + "\n" + dispatch_impl)

    extra_impl = """
EcReal __CLASS_NAME__::configValue
(
\tconst EcRealVector& values,
\tconst EcSizeT index,
\tconst EcReal defaultValue
) const
{
\treturn index < values.size() ? values[index] : defaultValue;
}

void __CLASS_NAME__::clearLastRuntimeDiagnostics(const EcBoolean validationOk)
{
\tm_lastDiagnostics.q_raw.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.dq_raw.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.ddq_raw.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.q_used.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.dq_used.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.ddq_used.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_M_raw.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_C_raw.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_G.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_F_viscous.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_F_coulomb.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_F_hold.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_F_total.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_M_used.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_C_used.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.tau_total.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.friction_sign.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.hold_indicator.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.motion_state.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.wM.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.wC.assign(kNumJoints, 0.0);
\tm_lastDiagnostics.validation_status.assign(kNumJoints, validationOk ? 1.0 : 0.0);
}

void __CLASS_NAME__::setRuntimeTorqueMode
(
\tconst EcInt32 mode
)
{
\tif (mode < LEGACY_RAW || mode > ROBUST_TIMED_RESERVED)
\t{
\t\tm_runtimeTorqueMode = LEGACY_RAW;
\t\treturn;
\t}
\tm_runtimeTorqueMode = mode;
}

void __CLASS_NAME__::setRuntimeNoTimeConfig
(
\tconst RuntimeNoTimeConfig& config
)
{
\tm_runtimeNoTimeConfig = config;
}

void __CLASS_NAME__::setSampleSmoothingConfig
(
\tconst SampleSmoothingConfig& config
)
{
\tm_sampleSmoothingConfig = config;
}

void __CLASS_NAME__::setRuntimeValidationConfig
(
\tconst RuntimeValidationConfig& config
)
{
\tm_runtimeValidationConfig = config;
}

void __CLASS_NAME__::setDdqClampConfig
(
\tconst DdqClampConfig& config
)
{
\tm_ddqClampConfig = config;
}

void __CLASS_NAME__::setFrictionStateConfig
(
\tconst FrictionStateConfig& config
)
{
\tm_frictionStateConfig = config;
}

void __CLASS_NAME__::setMCGateConfig
(
\tconst MCGateConfig& config
)
{
\tm_mcGateConfig = config;
}

void __CLASS_NAME__::resetRuntimeRobustState
(
)
{
\tm_qUsed.assign(kNumJoints, 0.0);
\tm_dqUsed.assign(kNumJoints, 0.0);
\tm_ddqUsed.assign(kNumJoints, 0.0);
\tm_qPrev.assign(kNumJoints, 0.0);
\tm_dqPrev.assign(kNumJoints, 0.0);
\tm_ddqPrev.assign(kNumJoints, 0.0);
\tm_tauM.assign(kNumJoints, 0.0);
\tm_tauC.assign(kNumJoints, 0.0);
\tm_tauG.assign(kNumJoints, 0.0);
\tm_tauF.assign(kNumJoints, 0.0);
\tm_tauTotal.assign(kNumJoints, 0.0);
\tm_tauFViscous.assign(kNumJoints, 0.0);
\tm_tauFCoulomb.assign(kNumJoints, 0.0);
\tm_tauFHold.assign(kNumJoints, 0.0);
\tm_frictionSign.assign(kNumJoints, 0.0);
\tm_holdIndicator.assign(kNumJoints, 0.0);
\tm_motionState.assign(kNumJoints, 0.0);
\tm_validationStatus.assign(kNumJoints, 0.0);
\tm_hasRobustStateInitialized = false;
\tclearLastRuntimeDiagnostics(false);
}

void __CLASS_NAME__::getLastRuntimeDiagnostics
(
\tRuntimeDiagnostics& diagnostics
) const
{
\tdiagnostics = m_lastDiagnostics;
}

void __CLASS_NAME__::getLastTorqueComponents
(
\tEcRealVector& tauM,
\tEcRealVector& tauC,
\tEcRealVector& tauG,
\tEcRealVector& tauF,
\tEcRealVector& tauTotal
) const
{
\ttauM = m_lastDiagnostics.tau_M_used;
\ttauC = m_lastDiagnostics.tau_C_used;
\ttauG = m_lastDiagnostics.tau_G;
\ttauF = m_lastDiagnostics.tau_F_total;
\ttauTotal = m_lastDiagnostics.tau_total;
}

void __CLASS_NAME__::getLastRuntimeSignals
(
\tEcRealVector& qUsed,
\tEcRealVector& dqUsed,
\tEcRealVector& ddqUsed,
\tEcRealVector& frictionSign,
\tEcRealVector& motionState
) const
{
\tqUsed = m_lastDiagnostics.q_used;
\tdqUsed = m_lastDiagnostics.dq_used;
\tddqUsed = m_lastDiagnostics.ddq_used;
\tfrictionSign = m_lastDiagnostics.friction_sign;
\tmotionState = m_lastDiagnostics.motion_state;
}

EcBoolean __CLASS_NAME__::validateRuntimeInputNoTime
(
\tconst EcRealVector& q,
\tconst EcRealVector& dq,
\tconst EcRealVector& ddq,
\tconst EcRealVector& parms,
\tEcRealVector& tau
)
{
\tif (tau.size() != m_NumJoints)
\t{
\t\ttau.assign(m_NumJoints, 0.0);
\t}
\telse
\t{
\t\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t\t{
\t\t\ttau[idx] = 0.0;
\t\t}
\t}
\tclearLastRuntimeDiagnostics(false);
\tif (q.size() != m_NumJoints || dq.size() != m_NumJoints || ddq.size() != m_NumJoints)
\t{
\t\treturn false;
\t}
\tif (!hasValidRuntimeParms(parms))
\t{
\t\treturn false;
\t}
\tif (m_runtimeNoTimeConfig.enableInputValidation && m_runtimeValidationConfig.enableFiniteCheck)
\t{
\t\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t\t{
\t\t\tif (!isfinite(q[idx]) || !isfinite(dq[idx]) || !isfinite(ddq[idx]))
\t\t\t{
\t\t\t\treturn false;
\t\t\t}
\t\t}
\t}
\tif (m_runtimeNoTimeConfig.enableInputValidation && m_runtimeValidationConfig.enableRadianRangeCheck)
\t{
\t\tEcSizeT suspiciousCount = 0;
\t\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t\t{
\t\t\tif (fabs(q[idx]) > m_runtimeValidationConfig.maxAbsQForRadianCheck)
\t\t\t{
\t\t\t\t++suspiciousCount;
\t\t\t}
\t\t}
\t\tif (suspiciousCount >= 2)
\t\t{
\t\t\treturn false;
\t\t}
\t}
\tif (m_runtimeNoTimeConfig.enableInputValidation && m_runtimeValidationConfig.enableGravityNormCheck)
\t{
\t\tconst EcReal norm = sqrt(m_gx * m_gx + m_gy * m_gy + m_gz * m_gz);
\t\tif (fabs(norm - m_runtimeValidationConfig.gravityNormExpected) > m_runtimeValidationConfig.gravityNormTolerance)
\t\t{
\t\t\treturn false;
\t\t}
\t}
\treturn true;
}

void __CLASS_NAME__::updateMotionStateNoTime()
{
\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t{
\t\tconst EcReal vOff = configValue(m_frictionStateConfig.vOff, idx, 0.01);
\t\tconst EcReal vOn = configValue(m_frictionStateConfig.vOn, idx, 0.03);
\t\tconst EcReal aOff = configValue(m_frictionStateConfig.aOff, idx, 0.2);
\t\tconst EcReal smoothVelocity = configValue(m_frictionStateConfig.smoothVelocity, idx, 0.02);
\t\tconst EcReal previousSign = idx < m_frictionSign.size() ? m_frictionSign[idx] : 0.0;
\t\tconst EcInt32 previousState = idx < m_motionState.size() ? static_cast<EcInt32>(m_motionState[idx]) : STATIC;
\t\tEcInt32 state = TRANSITION;
\t\tEcReal sign = previousSign;
\t\tEcReal hold = 0.0;
\t\tif (!(m_runtimeNoTimeConfig.enableFrictionStateMachine && m_frictionStateConfig.enabled))
\t\t{
\t\t\tif (fabs(m_dqUsed[idx]) < vOff && fabs(m_ddqUsed[idx]) < aOff)
\t\t\t{
\t\t\t\tstate = STATIC;
\t\t\t}
\t\t\telse if (m_dqUsed[idx] > 0.0)
\t\t\t{
\t\t\t\tstate = MOVING_POSITIVE;
\t\t\t}
\t\t\telse if (m_dqUsed[idx] < 0.0)
\t\t\t{
\t\t\t\tstate = MOVING_NEGATIVE;
\t\t\t}
\t\t}
\t\telse if (fabs(m_dqUsed[idx]) < vOff && fabs(m_ddqUsed[idx]) < aOff)
\t\t{
\t\t\tstate = STATIC;
\t\t}
\t\telse if (m_dqUsed[idx] > vOn)
\t\t{
\t\t\tstate = MOVING_POSITIVE;
\t\t}
\t\telse if (m_dqUsed[idx] < -vOn)
\t\t{
\t\t\tstate = MOVING_NEGATIVE;
\t\t}
\t\telse if (m_frictionStateConfig.enableHysteresis)
\t\t{
\t\t\tif (previousState == MOVING_POSITIVE && m_dqUsed[idx] > -vOff)
\t\t\t{
\t\t\t\tstate = MOVING_POSITIVE;
\t\t\t}
\t\t\telse if (previousState == MOVING_NEGATIVE && m_dqUsed[idx] < vOff)
\t\t\t{
\t\t\t\tstate = MOVING_NEGATIVE;
\t\t\t}
\t\t}
\t\tif (state == STATIC)
\t\t{
\t\t\tsign = 0.0;
\t\t\thold = (m_runtimeNoTimeConfig.enableHoldMode && m_frictionStateConfig.enableHoldMode) ? 1.0 : 0.0;
\t\t}
\t\telse if (state == MOVING_POSITIVE)
\t\t{
\t\t\tsign = 1.0;
\t\t}
\t\telse if (state == MOVING_NEGATIVE)
\t\t{
\t\t\tsign = -1.0;
\t\t}
\t\telse if (m_frictionStateConfig.enableSmoothSign && smoothVelocity > 0.0)
\t\t{
\t\t\tsign = tanh(m_dqUsed[idx] / smoothVelocity);
\t\t}
\t\tm_motionState[idx] = static_cast<EcReal>(state);
\t\tm_frictionSign[idx] = sign;
\t\tm_holdIndicator[idx] = hold;
\t}
}

void __CLASS_NAME__::computeFrictionTorqueRobustNoTimeInternal
(
\tconst EcRealVector& parms,
\tEcRealVector& tau
)
{
\tif (tau.size() != m_NumJoints)
\t{
\t\ttau.assign(m_NumJoints, 0.0);
\t}
\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t{
\t\tconst EcSizeT offset = idx * kRuntimeParamsPerJoint;
\t\tconst EcReal fv = parms[offset + 11];
\t\tconst EcReal fc = parms[offset + 12];
\t\tconst EcReal holdBias = configValue(m_frictionStateConfig.holdBias, idx, 0.0);
\t\tm_tauFViscous[idx] = fv * m_dqUsed[idx];
\t\tm_tauFCoulomb[idx] = fc * m_frictionSign[idx];
\t\tm_tauFHold[idx] = holdBias * m_holdIndicator[idx];
\t\ttau[idx] = m_tauFViscous[idx] + m_tauFCoulomb[idx] + m_tauFHold[idx];
\t}
}

EcBoolean __CLASS_NAME__::calculateEstimateJointToqruesRobustNoTimeInternal
(
\tconst EcRealVector& q,
\tconst EcRealVector& dq,
\tconst EcRealVector& ddq,
\tconst EcRealVector& parms,
\tEcRealVector& tau
)
{
\tif (!validateRuntimeInputNoTime(q, dq, ddq, parms, tau))
\t{
\t\treturn false;
\t}
\tconst EcRealVector& activeParms = activeRuntimeParms(parms);
\tclearLastRuntimeDiagnostics(true);
\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t{
\t\tm_lastDiagnostics.q_raw[idx] = q[idx];
\t\tm_lastDiagnostics.dq_raw[idx] = dq[idx];
\t\tm_lastDiagnostics.ddq_raw[idx] = ddq[idx];
\t}
\tif (!m_hasRobustStateInitialized)
\t{
\t\tm_qUsed = q;
\t\tm_dqUsed = dq;
\t\tm_ddqUsed = ddq;
\t}
\telse
\t{
\t\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t\t{
\t\t\tconst EcReal qAlpha = configValue(m_sampleSmoothingConfig.qAlpha, idx, 1.0);
\t\t\tconst EcReal dqAlpha = configValue(m_sampleSmoothingConfig.dqAlpha, idx, 1.0);
\t\t\tconst EcReal ddqAlpha = configValue(m_sampleSmoothingConfig.ddqAlpha, idx, 1.0);
\t\t\tm_qUsed[idx] = (m_runtimeNoTimeConfig.enableSampleSmoothing && m_sampleSmoothingConfig.enabled)
\t\t\t\t? qAlpha * q[idx] + (1.0 - qAlpha) * m_qPrev[idx] : q[idx];
\t\t\tm_dqUsed[idx] = (m_runtimeNoTimeConfig.enableSampleSmoothing && m_sampleSmoothingConfig.enabled)
\t\t\t\t? dqAlpha * dq[idx] + (1.0 - dqAlpha) * m_dqPrev[idx] : dq[idx];
\t\t\tm_ddqUsed[idx] = (m_runtimeNoTimeConfig.enableSampleSmoothing && m_sampleSmoothingConfig.enabled)
\t\t\t\t? ddqAlpha * ddq[idx] + (1.0 - ddqAlpha) * m_ddqPrev[idx] : ddq[idx];
\t\t}
\t}
\tif (m_runtimeNoTimeConfig.enableDdqClamp && m_ddqClampConfig.enabled)
\t{
\t\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t\t{
\t\t\tconst EcReal limit = fabs(configValue(m_ddqClampConfig.ddqLimit, idx, 50.0));
\t\t\tif (m_ddqUsed[idx] > limit)
\t\t\t{
\t\t\t\tm_ddqUsed[idx] = limit;
\t\t\t}
\t\t\telse if (m_ddqUsed[idx] < -limit)
\t\t\t{
\t\t\t\tm_ddqUsed[idx] = -limit;
\t\t\t}
\t\t}
\t}
\tupdateMotionStateNoTime();
\tcomputeMassTorque(m_qUsed, m_ddqUsed, activeParms, m_tauM);
\tcomputeCoriolisTorque(m_qUsed, m_dqUsed, activeParms, m_tauC);
\tcalculateGravityJointTorques(m_qUsed, activeParms, m_tauG);
\tcomputeFrictionTorqueRobustNoTimeInternal(activeParms, m_tauF);
\tif (tau.size() != m_NumJoints)
\t{
\t\ttau.assign(m_NumJoints, 0.0);
\t}
\tfor (EcSizeT idx = 0; idx < m_NumJoints; ++idx)
\t{
\t\tEcReal wM = 1.0;
\t\tEcReal wC = 1.0;
\t\tif (m_runtimeNoTimeConfig.enableMCGate && m_mcGateConfig.enabled)
\t\t{
\t\t\tconst EcInt32 state = static_cast<EcInt32>(m_motionState[idx]);
\t\t\tif (state == STATIC)
\t\t\t{
\t\t\t\twM = m_mcGateConfig.staticWM;
\t\t\t\twC = m_mcGateConfig.staticWC;
\t\t\t}
\t\t\telse if (state == TRANSITION)
\t\t\t{
\t\t\t\twM = m_mcGateConfig.transitionWM;
\t\t\t\twC = m_mcGateConfig.transitionWC;
\t\t\t}
\t\t\telse
\t\t\t{
\t\t\t\twM = m_mcGateConfig.dynamicWM;
\t\t\t\twC = m_mcGateConfig.dynamicWC;
\t\t\t}
\t\t}
\t\tconst EcReal tauMUsed = wM * m_tauM[idx];
\t\tconst EcReal tauCUsed = wC * m_tauC[idx];
\t\tm_tauTotal[idx] = tauMUsed + tauCUsed + m_tauG[idx] + m_tauF[idx];
\t\ttau[idx] = m_tauTotal[idx];
\t\tm_lastDiagnostics.q_used[idx] = m_qUsed[idx];
\t\tm_lastDiagnostics.dq_used[idx] = m_dqUsed[idx];
\t\tm_lastDiagnostics.ddq_used[idx] = m_ddqUsed[idx];
\t\tm_lastDiagnostics.tau_M_raw[idx] = m_tauM[idx];
\t\tm_lastDiagnostics.tau_C_raw[idx] = m_tauC[idx];
\t\tm_lastDiagnostics.tau_G[idx] = m_tauG[idx];
\t\tm_lastDiagnostics.tau_F_viscous[idx] = m_tauFViscous[idx];
\t\tm_lastDiagnostics.tau_F_coulomb[idx] = m_tauFCoulomb[idx];
\t\tm_lastDiagnostics.tau_F_hold[idx] = m_tauFHold[idx];
\t\tm_lastDiagnostics.tau_F_total[idx] = m_tauF[idx];
\t\tm_lastDiagnostics.tau_M_used[idx] = tauMUsed;
\t\tm_lastDiagnostics.tau_C_used[idx] = tauCUsed;
\t\tm_lastDiagnostics.tau_total[idx] = m_tauTotal[idx];
\t\tm_lastDiagnostics.friction_sign[idx] = m_frictionSign[idx];
\t\tm_lastDiagnostics.hold_indicator[idx] = m_holdIndicator[idx];
\t\tm_lastDiagnostics.motion_state[idx] = m_motionState[idx];
\t\tm_lastDiagnostics.wM[idx] = wM;
\t\tm_lastDiagnostics.wC[idx] = wC;
\t\tm_lastDiagnostics.validation_status[idx] = 1.0;
\t}
\tm_qPrev = m_qUsed;
\tm_dqPrev = m_dqUsed;
\tm_ddqPrev = m_ddqUsed;
\tm_hasRobustStateInitialized = true;
\treturn true;
}
""".replace("__CLASS_NAME__", class_name)

    source = source + "\n" + extra_impl
    cpp_path.write_text(source, encoding="utf-8")


def _extract_generated_function(
    source: str,
    function_name: str,
    replacement_signature: str,
    arg_names: list[str],
    output_name: str = "tau",
) -> str:
    marker = f"static int {function_name}("
    start = source.index(marker)
    body_start = source.index("{", start)
    depth = 0
    end = body_start
    for index in range(body_start, len(source)):
        char = source[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                end = index + 1
                break
    body = source[body_start + 1:end - 1]

    replacements = {
        r"if \(res\[0\]!=0\) res\[0\]\[(\d+)\]=([^;]+);": rf"{output_name}[\1] = \2;",
    }
    for arg_index, arg_name in enumerate(arg_names):
        replacements[rf"arg\[{arg_index}\]\? arg\[{arg_index}\]\[(\d+)\] : 0"] = rf"{arg_name}[\1]"
    for pattern, replacement in replacements.items():
        body = re.sub(pattern, replacement, body)
    body = body.replace("  return 0;\n", "")
    return replacement_signature + " {" + body + "\n}\n"


def _make_direct_core_code(generated_source: str) -> str:
    full_core = _extract_generated_function(
        generated_source,
        "casadi_f0",
        "static void calculateIdentifiedInverseDynamicsCore("
        "const double* q, const double* dq, const double* ddq, const double* gravity, double* tau)",
        ["q", "dq", "ddq", "gravity"],
    )
    rigid_core = _extract_generated_function(
        generated_source,
        "casadi_f1",
        "static void calculateIdentifiedRigidDynamicsCore("
        "const double* q, const double* dq, const double* ddq, const double* gravity, double* tau)",
        ["q", "dq", "ddq", "gravity"],
    )
    gravity_core = _extract_generated_function(
        generated_source,
        "casadi_f2",
        "static void calculateIdentifiedGravityTorqueCore("
        "const double* q, const double* gravity, double* tau)",
        ["q", "gravity"],
    )
    zero_gravity_rigid_core = _extract_generated_function(
        generated_source,
        "casadi_f3",
        "static void calculateIdentifiedZeroGravityRigidTorqueCore("
        "const double* q, const double* dq, const double* ddq, double* tau)",
        ["q", "dq", "ddq"],
    )
    mass_core = _extract_generated_function(
        generated_source,
        "casadi_f4",
        "static void calculateIdentifiedMassTorqueCore("
        "const double* q, const double* ddq, double* tau)",
        ["q", "ddq"],
    )
    coriolis_core = _extract_generated_function(
        generated_source,
        "casadi_f5",
        "static void calculateIdentifiedCoriolisTorqueCore("
        "const double* q, const double* dq, double* tau)",
        ["q", "dq"],
    )
    gravity_x_core = _extract_generated_function(
        generated_source,
        "casadi_f6",
        "static void calculateIdentifiedGravityXAxisTorqueCore("
        "const double* q, double* tau)",
        ["q"],
    )
    gravity_y_core = _extract_generated_function(
        generated_source,
        "casadi_f7",
        "static void calculateIdentifiedGravityYAxisTorqueCore("
        "const double* q, double* tau)",
        ["q"],
    )
    gravity_z_core = _extract_generated_function(
        generated_source,
        "casadi_f8",
        "static void calculateIdentifiedGravityZAxisTorqueCore("
        "const double* q, double* tau)",
        ["q"],
    )
    rigid_regressor_core = _extract_generated_function(
        generated_source,
        "casadi_f9",
        "static void calculateIdentifiedRigidRegressorRowMajorCore("
        "const double* q, const double* dq, const double* ddq, const double* gravity, double* out)",
        ["q", "dq", "ddq", "gravity"],
        output_name="out",
    )
    gravity_regressor_core = _extract_generated_function(
        generated_source,
        "casadi_f10",
        "static void calculateIdentifiedGravityRegressorRowMajorCore("
        "const double* q, const double* gravity, double* out)",
        ["q", "gravity"],
        output_name="out",
    )
    zero_gravity_rigid_regressor_core = _extract_generated_function(
        generated_source,
        "casadi_f11",
        "static void calculateIdentifiedZeroGravityRigidRegressorRowMajorCore("
        "const double* q, const double* dq, const double* ddq, double* out)",
        ["q", "dq", "ddq"],
        output_name="out",
    )
    return "\n".join(
        [
            "#include <math.h>",
            "",
            "static double signWithZero(double value)",
            "{",
            "\t// Treat speeds within 0.1 deg/s as stationary, then smoothly blend",
            "\t// the Coulomb term through zero to avoid hard sign flips.",
            "\tconst double deadzone = 1.7453292519943296e-03;  // 0.1 deg/s in rad/s",
            "\tconst double speed_abs = fabs(value);",
            "\tif (speed_abs <= deadzone)",
            "\t{",
            "\t\treturn 0.0;",
            "\t}",
            "\tconst double normalized = (speed_abs - deadzone) / deadzone;",
            "\tconst double smooth_sign = tanh(normalized);",
            "\treturn copysign(smooth_sign, value);",
            "}",
            "",
            "static double square(double value)",
            "{",
            "\treturn value * value;",
            "}",
            "",
            full_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            rigid_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            zero_gravity_rigid_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            mass_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            coriolis_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_x_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_y_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_z_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            rigid_regressor_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            gravity_regressor_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
            zero_gravity_rigid_regressor_core.replace("casadi_real", "double")
            .replace("casadi_sign", "signWithZero")
            .replace("casadi_sq", "square"),
        ]
    )


def _format_double(value: float) -> str:
    return f"{float(value):.17g}"


def _format_c_array(values: list[float] | np.ndarray, *, indent: str = "\t") -> str:
    numbers = [_format_double(value) for value in values]
    if not numbers:
        return "{}"
    rows = []
    for start in range(0, len(numbers), 6):
        rows.append(indent + ", ".join(numbers[start:start + 6]))
    return "{\n" + ",\n".join(rows) + "\n}"


def _format_c_matrix(values: list[list[float]] | np.ndarray) -> str:
    matrix = np.asarray(values, dtype=float)
    rows = []
    for row in matrix:
        rows.append("\t{" + ", ".join(_format_double(value) for value in row) + "}")
    return "{\n" + ",\n".join(rows) + "\n}"


def _feature_expression(feature_name: str, num_joints: int) -> str:
    one_joint_patterns = [
        (r"^q_(\d+)$", "q[{idx}]"),
        (r"^dq_(\d+)$", "dq[{idx}]"),
        (r"^ddq_(\d+)$", "ddq[{idx}]"),
        (r"^abs_dq_(\d+)$", "fabs(dq[{idx}])"),
        (r"^abs_ddq_(\d+)$", "fabs(ddq[{idx}])"),
        (r"^q_dq_prod_(\d+)$", "q[{idx}] * dq[{idx}]"),
        (r"^sin_q_(\d+)$", "sin(q[{idx}])"),
        (r"^cos_q_(\d+)$", "cos(q[{idx}])"),
    ]
    for pattern, expression_template in one_joint_patterns:
        match = re.match(pattern, feature_name)
        if match:
            joint_index = int(match.group(1)) - 1
            if joint_index < 0 or joint_index >= num_joints:
                raise ValueError(f"Feature {feature_name!r} references joint outside 1..{num_joints}.")
            return expression_template.format(idx=joint_index)

    match = re.match(r"^dq_pair_(\d+)_(\d+)$", feature_name)
    if match:
        first = int(match.group(1)) - 1
        second = int(match.group(2)) - 1
        if first < 0 or second < 0 or first >= num_joints or second >= num_joints:
            raise ValueError(f"Feature {feature_name!r} references joint outside 1..{num_joints}.")
        return f"dq[{first}] * dq[{second}]"

    if feature_name == "motion_magnitude":
        terms = " + ".join(f"dq[{joint_idx}] * dq[{joint_idx}]" for joint_idx in range(num_joints))
        return f"sqrt({terms})"

    raise ValueError(f"Unsupported MLP feature {feature_name!r}; cannot export C++ code.")


def _make_mlp_core_code(mlp_state: dict[str, Any], num_joints: int) -> str:
    feature_cols = list(mlp_state["feature_cols"])
    x_mean = np.asarray(mlp_state["x_mean"], dtype=float)
    x_scale = np.asarray(mlp_state["x_scale"], dtype=float)
    y_mean = np.asarray(mlp_state["y_mean"], dtype=float)
    y_scale = np.asarray(mlp_state["y_scale"], dtype=float)
    coefs = [np.asarray(coef, dtype=float) for coef in mlp_state["coefs"]]
    intercepts = [np.asarray(bias, dtype=float) for bias in mlp_state["intercepts"]]

    if mlp_state.get("activation") != "relu":
        raise ValueError("Only ReLU MLP compensation can be exported.")
    if len(coefs) != len(intercepts):
        raise ValueError("MLP coefficient/intercept layer count mismatch.")
    if len(feature_cols) != x_mean.size or len(feature_cols) != x_scale.size:
        raise ValueError("MLP feature column count does not match input scaler size.")
    if y_mean.size != num_joints or y_scale.size != num_joints:
        raise ValueError("MLP output scaler size does not match robot joint count.")
    if not coefs or coefs[-1].shape[1] != num_joints:
        raise ValueError("MLP output dimension does not match robot joint count.")
    if coefs[0].shape[0] != len(feature_cols):
        raise ValueError("MLP first layer input dimension does not match feature count.")

    layer_dims = [coefs[0].shape[0]]
    for layer_idx, coef in enumerate(coefs):
        if coef.shape[0] != layer_dims[-1]:
            raise ValueError(f"MLP layer {layer_idx} input dimension mismatch.")
        if intercepts[layer_idx].shape[0] != coef.shape[1]:
            raise ValueError(f"MLP layer {layer_idx} bias dimension mismatch.")
        layer_dims.append(coef.shape[1])

    lines = [
        f"static const int kMlpInputDim = {len(feature_cols)};",
        f"static const int kMlpOutputDim = {num_joints};",
    ]
    for layer_idx, dim in enumerate(layer_dims[1:]):
        lines.append(f"static const int kMlpLayer{layer_idx}Dim = {dim};")
    lines.extend(
        [
            "",
            f"static const double kMlpXMean[kMlpInputDim] = {_format_c_array(x_mean)};",
            f"static const double kMlpXScale[kMlpInputDim] = {_format_c_array(x_scale)};",
            f"static const double kMlpYMean[kMlpOutputDim] = {_format_c_array(y_mean)};",
            f"static const double kMlpYScale[kMlpOutputDim] = {_format_c_array(y_scale)};",
        ]
    )
    for layer_idx, (coef, bias) in enumerate(zip(coefs, intercepts)):
        input_dim = "kMlpInputDim" if layer_idx == 0 else f"kMlpLayer{layer_idx - 1}Dim"
        output_dim = "kMlpOutputDim" if layer_idx == len(coefs) - 1 else f"kMlpLayer{layer_idx}Dim"
        lines.extend(
            [
                "",
                f"static const double kMlpW{layer_idx}[{input_dim}][{output_dim}] = {_format_c_matrix(coef)};",
                f"static const double kMlpB{layer_idx}[{output_dim}] = {_format_c_array(bias)};",
            ]
        )

    lines.extend(
        [
            "",
            "static double relu(double value)",
            "{",
            "\treturn value > 0.0 ? value : 0.0;",
            "}",
            "",
            "static void calculateMlpResidualCompensationCore(",
            "\tconst double* q, const double* dq, const double* ddq, double* residual)",
            "{",
            "\tdouble features[kMlpInputDim];",
        ]
    )
    for feature_idx, feature_name in enumerate(feature_cols):
        lines.append(f"\tfeatures[{feature_idx}] = {_feature_expression(feature_name, num_joints)};")

    lines.extend(
        [
            "\tdouble h0[kMlpLayer0Dim];",
            "\tfor (int outIdx = 0; outIdx < kMlpLayer0Dim; ++outIdx)",
            "\t{",
            "\t\tdouble value = kMlpB0[outIdx];",
            "\t\tfor (int inIdx = 0; inIdx < kMlpInputDim; ++inIdx)",
            "\t\t{",
            "\t\t\tconst double normalized = (features[inIdx] - kMlpXMean[inIdx]) / kMlpXScale[inIdx];",
            "\t\t\tvalue += normalized * kMlpW0[inIdx][outIdx];",
            "\t\t}",
            "\t\th0[outIdx] = relu(value);",
            "\t}",
        ]
    )

    for layer_idx in range(1, len(coefs) - 1):
        prev = f"h{layer_idx - 1}"
        current = f"h{layer_idx}"
        prev_dim = f"kMlpLayer{layer_idx - 1}Dim"
        current_dim = f"kMlpLayer{layer_idx}Dim"
        lines.extend(
            [
                f"\tdouble {current}[{current_dim}];",
                f"\tfor (int outIdx = 0; outIdx < {current_dim}; ++outIdx)",
                "\t{",
                f"\t\tdouble value = kMlpB{layer_idx}[outIdx];",
                f"\t\tfor (int inIdx = 0; inIdx < {prev_dim}; ++inIdx)",
                "\t\t{",
                f"\t\t\tvalue += {prev}[inIdx] * kMlpW{layer_idx}[inIdx][outIdx];",
                "\t\t}",
                f"\t\t{current}[outIdx] = relu(value);",
                "\t}",
            ]
        )

    output_layer_idx = len(coefs) - 1
    prev = f"h{output_layer_idx - 1}"
    prev_dim = f"kMlpLayer{output_layer_idx - 1}Dim"
    lines.extend(
        [
            "\tfor (int outIdx = 0; outIdx < kMlpOutputDim; ++outIdx)",
            "\t{",
            f"\t\tdouble value = kMlpB{output_layer_idx}[outIdx];",
            f"\t\tfor (int inIdx = 0; inIdx < {prev_dim}; ++inIdx)",
            "\t\t{",
            f"\t\t\tvalue += {prev}[inIdx] * kMlpW{output_layer_idx}[inIdx][outIdx];",
            "\t\t}",
            "\t\tresidual[outIdx] = value * kMlpYScale[outIdx] + kMlpYMean[outIdx];",
            "\t}",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def export_identified_inverse_dynamics_cpp(
    *,
    robot_model,
    result: dict,
    urdf_path: Path,
    output_dir: Path,
    result_stem: str,
    mlp_compensator=None,
    generation_metadata: dict[str, Any] | None = None,
    class_name: str = "identifiedDynamics",
    parameter_vector: InertialParameterVector | None = None,
    gravity_config: GravityConfig | str | np.ndarray | list[float] | None = None,
    payload_model=None,
    payload_mode: str | PayloadMode = PayloadMode.NONE,
    payload_frame_transform: np.ndarray | None = None,
) -> dict[str, Path]:
    """
    Export identified inverse-dynamics code into `output_dir`.

    Parameters
    ----------
    robot_model
        The loaded robot model whose Pinocchio model carries the chosen gravity.
    result : dict
        Identification result containing `theta_hat_full`.
    urdf_path : Path
        Kept for API clarity and metadata symmetry with the caller.
    output_dir : Path
        Destination directory.
    result_stem : str
        Usually `real` or `synthetic`.
    mlp_compensator
        当前阶段保留该参数仅为了 API 兼容；导出链默认忽略残差补偿，只生成纯物理模型。
    generation_metadata
        Metadata written into the generated files as comments. This is where
        timestamp/source/mode information belongs, while filenames stay stable.
    class_name : str
        Stable RTOSAlgorithm-side class name to generate.

    Returns
    -------
    dict[str, Path]
        Paths for the generated C source, C header, and C++ wrapper.
    """
    del urdf_path  # Pinocchio model is already built and gravity-configured by the caller.

    if pin is None:
        raise RuntimeError("Pinocchio is not available; cannot generate inverse-dynamics code.")

    try:
        import casadi as ca
        import pinocchio.casadi as cpin
    except ImportError as exc:
        raise RuntimeError(
            "CasADi and pinocchio.casadi are required. Run this pipeline in the "
            "`pinocchio_py` conda environment."
        ) from exc

    output_dir.mkdir(parents=True, exist_ok=True)
    temp_dir = output_dir / ".codegen_tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    num_joints = int(robot_model.num_joints)
    effective_parameter_vector = (
        parameter_vector.copy()
        if parameter_vector is not None
        else InertialParameterVector.from_identification_result(result, num_joints)
    )
    effective_payload_mode = PayloadMode.from_value(
        payload_mode.value if isinstance(payload_mode, PayloadMode) else payload_mode
    )
    if payload_model is not None and effective_payload_mode == PayloadMode.LUMPED_LAST_LINK:
        effective_parameter_vector.add_to_link(
            num_joints - 1,
            payload_model.to_inertial_parameter_delta(frame_transform=payload_frame_transform),
        )
    elif payload_model is not None and effective_payload_mode == PayloadMode.EXTERNAL_WRENCH:
        raise NotImplementedError(
            "C++ export currently supports payload_mode='lumped_last_link' only. "
            "Use the Python runtime model for external-wrench payload compensation."
        )

    theta_full = np.asarray(effective_parameter_vector.to_theta_full(with_friction=True), dtype=float)
    expected_size = 12 * num_joints
    if theta_full.shape != (expected_size,):
        raise ValueError(f"Expected theta_hat_full length {expected_size}, got {theta_full.shape[0]}.")

    num_rigid_params = 10 * num_joints
    theta_rigid = ca.DM(theta_full[:num_rigid_params])
    viscous = theta_full[num_rigid_params:num_rigid_params + num_joints]
    coulomb = theta_full[num_rigid_params + num_joints:]

    cmodel = cpin.Model(robot_model.pinocchio_model)
    cdata = cmodel.createData()

    q = ca.SX.sym("q", num_joints)
    dq = ca.SX.sym("dq", num_joints)
    ddq = ca.SX.sym("ddq", num_joints)

    gravity = ca.SX.sym("gravity", 3)
    gx, gy, gz = gravity[0], gravity[1], gravity[2]

    zero_dq = ca.SX.zeros(num_joints, 1)
    zero_ddq = ca.SX.zeros(num_joints, 1)
    zero_gravity = ca.SX.zeros(3, 1)
    gravity_x = ca.vertcat(ca.SX(1.0), ca.SX(0.0), ca.SX(0.0))
    gravity_y = ca.vertcat(ca.SX(0.0), ca.SX(1.0), ca.SX(0.0))
    gravity_z = ca.vertcat(ca.SX(0.0), ca.SX(0.0), ca.SX(1.0))

    cmodel.gravity.linear = zero_gravity
    y_m = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, ddq)
    y_c = cpin.computeJointTorqueRegressor(cmodel, cdata, q, dq, zero_ddq)

    cmodel.gravity.linear = gravity_x
    y_gx = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, zero_ddq)
    cmodel.gravity.linear = gravity_y
    y_gy = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, zero_ddq)
    cmodel.gravity.linear = gravity_z
    y_gz = cpin.computeJointTorqueRegressor(cmodel, cdata, q, zero_dq, zero_ddq)

    rigid_regressor = y_m + y_c + gx * y_gx + gy * y_gy + gz * y_gz
    gravity_regressor = gx * y_gx + gy * y_gy + gz * y_gz
    zero_gravity_rigid_regressor = y_m + y_c

    rigid_tau = ca.mtimes(rigid_regressor, theta_rigid)
    gravity_tau = ca.mtimes(gravity_regressor, theta_rigid)
    zero_gravity_rigid_tau = ca.mtimes(zero_gravity_rigid_regressor, theta_rigid)
    friction_tau = ca.vertcat(
        *[
            viscous[joint_idx] * dq[joint_idx] + coulomb[joint_idx] * ca.sign(dq[joint_idx])
            for joint_idx in range(num_joints)
        ]
    )
    tau = rigid_tau + friction_tau

    function_name = "identified_inverse_dynamics"
    function = ca.Function(
        function_name,
        [q, dq, ddq, gravity],
        [tau],
        ["q", "dq", "ddq", "gravity"],
        ["tau"],
    )
    rigid_function = ca.Function(
        "identified_inverse_dynamics_rigid",
        [q, dq, ddq, gravity],
        [rigid_tau],
        ["q", "dq", "ddq", "gravity"],
        ["tau"],
    )
    gravity_function = ca.Function(
        "identified_gravity_torques",
        [q, gravity],
        [gravity_tau],
        ["q", "gravity"],
        ["tau"],
    )
    zero_gravity_rigid_function = ca.Function(
        "identified_zero_gravity_rigid_torques",
        [q, dq, ddq],
        [zero_gravity_rigid_tau],
        ["q", "dq", "ddq"],
        ["tau"],
    )
    mass_function = ca.Function(
        "identified_mass_torques",
        [q, ddq],
        [ca.mtimes(y_m, theta_rigid)],
        ["q", "ddq"],
        ["tau"],
    )
    coriolis_function = ca.Function(
        "identified_coriolis_torques",
        [q, dq],
        [ca.mtimes(y_c, theta_rigid)],
        ["q", "dq"],
        ["tau"],
    )
    gravity_x_function = ca.Function(
        "identified_gravity_xaxis_torques",
        [q],
        [ca.mtimes(y_gx, theta_rigid)],
        ["q"],
        ["tau"],
    )
    gravity_y_function = ca.Function(
        "identified_gravity_yaxis_torques",
        [q],
        [ca.mtimes(y_gy, theta_rigid)],
        ["q"],
        ["tau"],
    )
    gravity_z_function = ca.Function(
        "identified_gravity_zaxis_torques",
        [q],
        [ca.mtimes(y_gz, theta_rigid)],
        ["q"],
        ["tau"],
    )
    rigid_regressor_row_major = ca.vertcat(
        *[rigid_regressor[row_idx, col_idx] for row_idx in range(num_joints) for col_idx in range(num_rigid_params)]
    )
    gravity_regressor_row_major = ca.vertcat(
        *[gravity_regressor[row_idx, col_idx] for row_idx in range(num_joints) for col_idx in range(num_rigid_params)]
    )
    zero_gravity_rigid_regressor_row_major = ca.vertcat(
        *[
            zero_gravity_rigid_regressor[row_idx, col_idx]
            for row_idx in range(num_joints)
            for col_idx in range(num_rigid_params)
        ]
    )
    rigid_regressor_function = ca.Function(
        "identified_rigid_regressor_row_major",
        [q, dq, ddq, gravity],
        [rigid_regressor_row_major],
        ["q", "dq", "ddq", "gravity"],
        ["out"],
    )
    gravity_regressor_function = ca.Function(
        "identified_gravity_regressor_row_major",
        [q, gravity],
        [gravity_regressor_row_major],
        ["q", "gravity"],
        ["out"],
    )
    zero_gravity_rigid_regressor_function = ca.Function(
        "identified_zero_gravity_rigid_regressor_row_major",
        [q, dq, ddq],
        [zero_gravity_rigid_regressor_row_major],
        ["q", "dq", "ddq"],
        ["out"],
    )

    c_filename = f"identified_inverse_dynamics_{result_stem}_core.c"
    project_header_filename = f"{class_name}.h"
    project_cpp_filename = f"{class_name}.cpp"

    # CasADi's generator validates the raw filename as a C identifier-like name,
    # so generate from inside the output directory instead of passing a path.
    with _pushd(temp_dir):
        codegen = ca.CodeGenerator(c_filename, {"with_header": True})
        codegen.add(function)
        codegen.add(rigid_function)
        codegen.add(gravity_function)
        codegen.add(zero_gravity_rigid_function)
        codegen.add(mass_function)
        codegen.add(coriolis_function)
        codegen.add(gravity_x_function)
        codegen.add(gravity_y_function)
        codegen.add(gravity_z_function)
        codegen.add(rigid_regressor_function)
        codegen.add(gravity_regressor_function)
        codegen.add(zero_gravity_rigid_regressor_function)
        codegen.generate()

    generated_core_code = _make_direct_core_code((temp_dir / c_filename).read_text(encoding="utf-8"))
    if temp_dir.exists():
        for temp_file in temp_dir.iterdir():
            temp_file.unlink()
        temp_dir.rmdir()

    del mlp_compensator

    default_runtime_parms = np.zeros(num_joints * 13, dtype=float)
    for joint_idx in range(num_joints):
        rigid_offset = 10 * joint_idx
        runtime_offset = 13 * joint_idx
        phi = theta_full[rigid_offset:rigid_offset + 10]
        default_runtime_parms[runtime_offset + 0] = phi[4]
        default_runtime_parms[runtime_offset + 1] = phi[5]
        default_runtime_parms[runtime_offset + 2] = phi[6]
        default_runtime_parms[runtime_offset + 3] = phi[7]
        default_runtime_parms[runtime_offset + 4] = phi[8]
        default_runtime_parms[runtime_offset + 5] = phi[9]
        default_runtime_parms[runtime_offset + 6] = phi[1]
        default_runtime_parms[runtime_offset + 7] = phi[2]
        default_runtime_parms[runtime_offset + 8] = phi[3]
        default_runtime_parms[runtime_offset + 9] = phi[0]
        default_runtime_parms[runtime_offset + 10] = 0.0
        default_runtime_parms[runtime_offset + 11] = viscous[joint_idx]
        default_runtime_parms[runtime_offset + 12] = coulomb[joint_idx]

    project_header_path = output_dir / project_header_filename
    project_cpp_path = output_dir / project_cpp_filename
    _clear_stale_generated_project_files(
        output_dir,
        keep_paths={project_header_path, project_cpp_path},
    )
    _write_project_header(project_header_path, class_name, num_joints, generation_metadata)
    _write_project_cpp(
        project_cpp_path,
        class_name,
        num_joints,
        np.asarray(GravityConfig.from_any(gravity_config or robot_model.gravity_vector).gravity_vector_base, dtype=float),
        default_runtime_parms,
        generated_core_code,
        generation_metadata,
    )
    _inject_runtime_robust_header(project_header_path, class_name)
    _inject_runtime_robust_cpp(project_cpp_path, class_name)

    return {
        "project_header": project_header_path,
        "project_cpp": project_cpp_path,
    }
